### ISSUE TITLE
关于操作系统的疑问

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/secretpad#102]
### Issue Type

Others

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

centos7.9

### All_in_one Version

0.2.0beta

### Module type

others

### Module version

Easy-PSI-0.2.0beta.tar.gz

### What happend and What you expected to happen.

```shell
针对Easy-PSI-XXXX.tar.gz部署环境疑问：

疑问1：是否支持SUSE操作系统，如果支持的话，具体支持哪些版本？

疑问2：是否支持新创环境，麒麟系统ARM架构支持吗？
```

### Log output.

```shell
无
```

**Comment by zimu-yuxi** [comment]
1.这个没有验证过，目前是有什么需求吗？
2.暂不支持arm

**Comment by coderSun20201112** [comment]
> 1.这个没有验证过，目前是有什么需求吗？ 2.暂不支持arm

支持国产麒麟系统吗，X86架构支持吗？

**Comment by zimu-yuxi** [comment]
> > 1.这个没有验证过，目前是有什么需求吗？ 2.暂不支持arm
> 
> 支持国产麒麟系统吗，X86架构支持吗？

支持x86架构，但是信创的x86我们这边暂时没有验证，你这边可以尝试部署下

**Comment by coderSun20201112** [comment]
> > > 1.这个没有验证过，目前是有什么需求吗？ 2.暂不支持arm
> > 
> > 
> > 支持国产麒麟系统吗，X86架构支持吗？
> 
> 支持x86架构，但是信创的x86我们这边暂时没有验证，你这边可以尝试部署下

好的，谢谢
