### ISSUE TITLE
二次开发调试问题

### ISSUE THREAD

**Issue by Sept98** [secretflow/secretpad#109]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Link to Relevant Documentation

https://github.com/secretflow/secretpad/issues/34

### Question Details

```shell
请问，secretpad-0.8.x 本地已经启动了kuscia，按照已有issue中的配置进行了操作，包括复制certs和secretpad.sqlite至config与db文件夹中，配置了jvm启动参数和环境变量，然后启动时报错：
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataResourceAspect': Unsatisfied dependency expressed through field 'dataResourceAuth': Error creating bean with name 'defaultDataResourceAuth': Unsatisfied dependency expressed through field 'dataResourceProjectAuth': Error creating bean with name 'dataResourceProjectAuth': Unsatisfied dependency expressed through field 'projectService': Error creating bean with name 'projectServiceImpl': Injection of resource dependencies failed。
请问是哪里配置错了呀
```

**Comment by Sept98** [comment]
idea配置：
![图片](https://github.com/user-attachments/assets/e176ac9b-e8a9-4dea-a973-37428ba828f3)
具体报错：
![图片](https://github.com/user-attachments/assets/47b54239-603f-47ae-b771-0412dbbd49a0)

**Comment by wenkesong-li** [comment]
你好，请参照本地开发调试文档进行：https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.8.1b0/development/ru_in_idea_cn

**Comment by Sept98** [comment]
请问这个是linux也行么，我看上面写的是只针对MAC

**Comment by wenkesong-li** [comment]
> 请问这个是linux也行么，我看上面写的是只针对MAC

可以try一下，写了mac是因为我们推荐使用mac，但是pad的实现是java，不区分平台

**Comment by Sept98** [comment]
好的，谢谢
