### ISSUE TITLE
oss数据源，endpoint配置成内网的地址会出现禁止内网IP的报错

### ISSUE THREAD

**Issue by john8628** [secretflow/secretpad#110]
### Issue Type

Feature

### Have you searched for existing issues?

Yes

### Link to Relevant Documentation

https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.7.0b0/p2p_deploy/function_description/data_source

### Question Details

```shell
在pad中注册oss数据源；因为ak/sk是对应是内网的；所以endpoint，需要配置成内网Endpoint(oss-us-west-1-internal.aliyuncs.com);但是提交的时候会出现禁止内网IP的报错
```

**Comment by aokaokd** [comment]
具体的报错截图发一下吧

**Comment by john8628** [comment]
很容易复现的 ![image](https://github.com/user-attachments/assets/f7f98fbe-e725-41b7-8744-13401376a405)

**Comment by aokaokd** [comment]
这个是被拦截了，我们内部讨论下，晚些给你回复

**Comment by aokaokd** [comment]
目前没有调整的排期，这了改成false就好了
![image](https://github.com/user-attachments/assets/f093857a-fb8e-47e7-ac1c-779343ece02c)

**Comment by john8628** [comment]
好的， 我这边时下

**Comment by john8628** [comment]
@aokaokd 改成false之后，还是不工作啊； The bucket you access does not belong to you.

**Comment by john8628** [comment]
@aokaokd @zimu-yuxi  感谢两位，已经OK了
1: 在oss配置权限，除了getObject,ListObject,还需要getBucketAcl；2:在配置文件，不能使用即是文件也是路径的文件；
