### ISSUE TITLE
节点已经同意邀请加入项目，但是显示待同意；

### ISSUE THREAD

**Issue by john8628** [secretflow/secretpad#117]
### Issue Type

Api Usage

### Have you searched for existing issues?

Yes

### Question Details

```shell
A节点创建项目，邀请B参加 B节点同意，但是项目显示未加入,导致项目显示不可用；
```

**Comment by john8628** [comment]
![image](https://github.com/user-attachments/assets/8d007cff-45b6-4353-916b-ec7d969671bc)

**Comment by zimu-yuxi** [comment]
在secretpad容器内sync-data.log日志看下，参考[此处](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.9.0b0/deployment/log#id4)

**Comment by john8628** [comment]
> 在secretpad容器内sync-data.log日志看下，参考[此处](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.9.0b0/deployment/log#id4)

日志挺多的，主要是关注哪些信息啊？
