### ISSUE TITLE
secretpad0.9版本 代码编译出错

### ISSUE THREAD

**Issue by wangzeyu135798** [secretflow/secretpad#118]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

mac

### All_in_one Version

---

### Kuscia Version

---

### What happend and What you expected to happen.

```shell
你好，我在编译secretpad0.9版本代码的时候发生错误。
环境：
secretpad 0.9
java      1.8
maven     3.9.x
os        mac
使用mvn clean install -Dmaven.test.skip=true发生如下错误，请问原因是什么，该如何解决？
Deleting /Users/wangzeyu/Desktop/zjcode/secretpad9/secretpad/secretpad-common (includes = [secretpad-service/**/com/, secretpad-service/**/org/secretflow/proto/, secretpad-api/client-java-kusciaapi/src/main/java/secretflow/, secretpad-api/client-java-kusciaapi/src/main/java/org/secretflow/v1alpha1/common/, secretpad-api/client-java-kusciaapi/src/main/java/org/secretflow/v1alpha1/kusciaapi/, secretpad-web/config/, secretpad-web/db/, **/*.crt, **/*.key, **/*.srl, **/*.csr], excludes = [])
[INFO] 
[INFO] --- jacoco:0.8.11:prepare-agent (prepare-agent) @ secretpad-common ---
[INFO] argLine set to -javaagent:/Users/wangzeyu/mavenrepo/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11-runtime.jar=destfile=/Users/wangzeyu/Desktop/zjcode/secretpad9/secretpad/secretpad-common/target/jacoco.exec
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ secretpad-common ---
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO] Copying 5 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ secretpad-common ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 79 source files with javac [debug release 17] to target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for secretpad-parent 0.0.1-SNAPSHOT:
[INFO] 
[INFO] secretpad-parent ................................... SUCCESS [  0.381 s]
[INFO] secretpad-common ................................... FAILURE [  0.208 s]
[INFO] secretpad-api ...................................... SKIPPED
[INFO] client-java-kusciaapi .............................. SKIPPED
[INFO] secretpad-persistence .............................. SKIPPED
[INFO] secretpad-manager .................................. SKIPPED
[INFO] secretpad-service .................................. SKIPPED
[INFO] secretpad-web ...................................... SKIPPED
[INFO] client-java-secretpad .............................. SKIPPED
[INFO] test ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.870 s
[INFO] Finished at: 2024-08-15T10:21:14+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project secretpad-common: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :secretpad-common
```

### Log output.

```shell
Deleting /Users/wangzeyu/Desktop/zjcode/secretpad9/secretpad/secretpad-common (includes = [secretpad-service/**/com/, secretpad-service/**/org/secretflow/proto/, secretpad-api/client-java-kusciaapi/src/main/java/secretflow/, secretpad-api/client-java-kusciaapi/src/main/java/org/secretflow/v1alpha1/common/, secretpad-api/client-java-kusciaapi/src/main/java/org/secretflow/v1alpha1/kusciaapi/, secretpad-web/config/, secretpad-web/db/, **/*.crt, **/*.key, **/*.srl, **/*.csr], excludes = [])
[INFO] 
[INFO] --- jacoco:0.8.11:prepare-agent (prepare-agent) @ secretpad-common ---
[INFO] argLine set to -javaagent:/Users/wangzeyu/mavenrepo/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11-runtime.jar=destfile=/Users/wangzeyu/Desktop/zjcode/secretpad9/secretpad/secretpad-common/target/jacoco.exec
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ secretpad-common ---
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO] Copying 5 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ secretpad-common ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 79 source files with javac [debug release 17] to target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for secretpad-parent 0.0.1-SNAPSHOT:
[INFO] 
[INFO] secretpad-parent ................................... SUCCESS [  0.381 s]
[INFO] secretpad-common ................................... FAILURE [  0.208 s]
[INFO] secretpad-api ...................................... SKIPPED
[INFO] client-java-kusciaapi .............................. SKIPPED
[INFO] secretpad-persistence .............................. SKIPPED
[INFO] secretpad-manager .................................. SKIPPED
[INFO] secretpad-service .................................. SKIPPED
[INFO] secretpad-web ...................................... SKIPPED
[INFO] client-java-secretpad .............................. SKIPPED
[INFO] test ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.870 s
[INFO] Finished at: 2024-08-15T10:21:14+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project secretpad-common: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :secretpad-common
```

**Comment by zimu-yuxi** [comment]
Java jdk17

**Comment by wangzeyu135798** [comment]
cd secretflow-allinone-package-latest
 bash install.sh autonomy -P notls

**Comment by wangzul** [comment]
> cd secretflow-allinone-package-latest bash install.sh autonomy -P notls 出现相关容器启动不起来的情况，容器日志如下： 2024-08-15 16:54:49.217 INFO modules/coredns.go:186 CoreDNS is ready 2024-08-15 16:54:49.217 INFO modules/modules.go:115 Add destroyFunc [k3s] 2024-08-15 16:54:49.217 WARN datastore/datastore_endpoint_check.go:47 Kuscia 'datastoreEndpoint' config is empty, will use sqlite. 2024-08-15 16:54:49.217 INFO supervisor/supervisor.go:75 [k3s] start and watch subprocess 2024-08-15 16:54:49.217 INFO supervisor/supervisor.go:101 [k3s] try to start new process 2024-08-15 16:54:49.217 INFO process/process.go:76 Set pid[23] oom score adj to -800 2024-08-15 16:54:49.260 WARN supervisor/supervisor.go:155 Process [k3s][23] exit with error: exit status 1 2024-08-15 16:54:49.260 WARN supervisor/supervisor.go:110 [k3s] run process failed, detail -> process [k3s][23] only existed 42 ms, less than 3000 ms, with error: exit status 1 2024-08-15 16:54:49.260 ERROR modules/k3s.go:278 startup process failed at first time, so stop at once, error: process [k3s][23] only existed 42 ms, less than 3000 ms, with error: exit status 1 2024-08-15 16:54:49.260 ERROR modules/k3s.go:283 context canceled 2024-08-15 16:54:49.260 FATAL modules/modules.go:184 error building kubernetes client config from token, detail-> build config from flags failed, detail-> stat /home/kuscia/etc/kubeconfig: no such file or directory 2024-08-15 16:54:49.260 WARN supervisor/supervisor.go:175 Context done, begin to stop process [k3s][23]

你可以参考我们官网allinone文档来重新调整部署命令。
https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.8.0b0/p2p_deploy/platform_installation_guidelines

**Comment by wangzeyu135798** [comment]
> > cd secretflow-allinone-package-latest bash install.sh autonomy -P notls 出现相关容器启动不起来的情况，容器日志如下： 2024-08-15 16:54:49.217 INFO modules/coredns.go:186 CoreDNS is ready 2024-08-15 16:54:49.217 INFO modules/modules.go:115 Add destroyFunc [k3s] 2024-08-15 16:54:49.217 WARN datastore/datastore_endpoint_check.go:47 Kuscia 'datastoreEndpoint' config is empty, will use sqlite. 2024-08-15 16:54:49.217 INFO supervisor/supervisor.go:75 [k3s] start and watch subprocess 2024-08-15 16:54:49.217 INFO supervisor/supervisor.go:101 [k3s] try to start new process 2024-08-15 16:54:49.217 INFO process/process.go:76 Set pid[23] oom score adj to -800 2024-08-15 16:54:49.260 WARN supervisor/supervisor.go:155 Process [k3s][23] exit with error: exit status 1 2024-08-15 16:54:49.260 WARN supervisor/supervisor.go:110 [k3s] run process failed, detail -> process [k3s][23] only existed 42 ms, less than 3000 ms, with error: exit status 1 2024-08-15 16:54:49.260 ERROR modules/k3s.go:278 startup process failed at first time, so stop at once, error: process [k3s][23] only existed 42 ms, less than 3000 ms, with error: exit status 1 2024-08-15 16:54:49.260 ERROR modules/k3s.go:283 context canceled 2024-08-15 16:54:49.260 FATAL modules/modules.go:184 error building kubernetes client config from token, detail-> build config from flags failed, detail-> stat /home/kuscia/etc/kubeconfig: no such file or directory 2024-08-15 16:54:49.260 WARN supervisor/supervisor.go:175 Context done, begin to stop process [k3s][23]
> 
> 你可以参考我们官网allinone文档来重新调整部署命令。 https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.8.0b0/p2p_deploy/platform_installation_guidelines

我这边是想secretpad0.9本地调试，解压mvp包进入文件之后执行的是 bash install.sh autonomy -P notls，出现上面的报错。并不是想按照all in one的模式进行部署。

**Comment by zimu-yuxi** [comment]
1.如果你只要参考secretpad0.9本地调试文档，那么部署脚本应该是 bash install.sh master -P notls
2.如果你想要执行bash install.sh autonomy -P notls，请参考官网allinone文档P2P的文档
3.请问secretpad本地调试的目的是什么呢？

**Comment by wangzeyu135798** [comment]
> 1.如果你只要参考secretpad0.9本地调试文档，那么部署脚本应该是 bash install.sh master -P notls 2.如果你想要执行bash install.sh autonomy -P notls，请参考官网allinone文档P2P的文档 3.请问secretpad本地调试的目的是什么呢？

1. 本地部署文档里，我是按照p2p模式启动的，使用的是文档中的install.sh autonomy, 就会遇到下面第一张图的问题，第二张图是容器的日志。
<img width="1217" alt="image" src="https://github.com/user-attachments/assets/baf53a48-26a7-4623-a42e-740298f24d53">
<img width="1524" alt="image" src="https://github.com/user-attachments/assets/e02e6ebf-4ebb-49fc-aab4-9866f238275c">

**Comment by zimu-yuxi** [comment]
1.docker版本提供一下
2.宿主机资源df -h看下

**Comment by wangzeyu135798** [comment]
1、
<img width="290" alt="image" src="https://github.com/user-attachments/assets/041bcb58-7c4f-4867-b689-956d5feb39d0">

2、
<img width="913" alt="image" src="https://github.com/user-attachments/assets/c98797f8-78c6-432c-88a2-cf78d5538edb">
