### ISSUE TITLE
过程中操作日志可以在哪里查看

### ISSUE THREAD

**Issue by EightMonth** [secretflow/secretpad#120]
### Issue Type

Others

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

ubuntu 18.04

### All_in_one Version

v0.8

### Kuscia Version

0.7

### What happend and What you expected to happen.

```shell
有两个问题想要请教下：
1.无法通过secretpad查看从节点加载数据时的加密过程，等于无法向他方解释数据是被加密进行运算的，而不是明文
2.无法通过secretpad查看数据被使用结束时销毁，现在进入secretpad容器内部的data目录，是可以看到明文数据与密文数据的，如alice.csv 、 alice.scv.encrypted

PS:个人小建议，可以在引擎日志旁边加一个数据处理过程的日志以及验证，这样可以增加小白对隐私计算的可信度。
```

### Log output.

```shell
无
```

**Comment by Chrisdehe** [comment]
@EightMonth 感谢tips，目前日志存放路径可以查看：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.10.0b0/deployment/logdescription

**Comment by EightMonth** [comment]
请问我问题的答案是什么呢

**Comment by 383004576** [comment]
1. 加密是在运算时基于不同组件实现的例如同态加密，节点上传加载的csv数据只是指向数据源。
2. 通常情况下数据源都在用户自己的节点环境，使用完不会销毁。

**Comment by EightMonth** [comment]
1.我理解数据都是在alice、bob节点上，然后中心节点请求获取alice、bob节点的数据，alice、bob节点返回加密后的数据给到中心节点。我想请问这个加密过程，有可以看的已被加密的证据么，比如日志记录了加密后的输出一类的。
2，另外中心节点有没有日志记录从节点请求回来的加密数据针对性的使用，使用过程中有没有进行保存或其它类的另外操作

**Comment by 383004576** [comment]
1. 中心节点不会获取参与方的数据，只进行调度管理。
2.节点日志里不会对数据进行打印，可以自己跑一下PSI任务，手动加日志打印相关信息。

**Comment by EightMonth** [comment]
请问中心部署模式的交互模式是怎么样，有相关介绍图么，我只在官网找到了二方、三方PSI的交互图

**Comment by 383004576** [comment]
可以参考：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.10.0b0/reference/architecture_cn
![image](https://github.com/user-attachments/assets/8e0b5d9d-f79b-41ea-b2ca-43bbca39c970)

**Comment by EightMonth** [comment]
好的，感谢
