### ISSUE TITLE
修改secretpad源码，在all in one部署的secretpad容器下替换secretpad.jar包，报错

### ISSUE THREAD

**Issue by wangzeyu135798** [secretflow/secretpad#123]
### Issue Type

Running

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

centos7

### All_in_one Version

1.5.0

### Module type

secretflow

### Module version

secretpad0.6 kuscia0.7 secretflow1.5

### What happend and What you expected to happen.

```shell
修改secretpad源码，在all in one部署的secretpad容器下替换secretpad.jar包，报错
```

### Log output.

```shell
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:20:56.888989569Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:20:57.532491307Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:20:58.229219529Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:20:59.160369578Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:21:00.452656311Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:21:02.601480791Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:21:06.356840792Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:21:13.256346946Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:21:26.555750703Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:03.196171753Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:03.830568924Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:04.525968894Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:05.432581647Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:06.735496165Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:08.83542295Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:12.532852209Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:19.502435674Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:32.820677426Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:22:58.904407502Z"}
{"log":"[FATAL tini (6)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:23:50.632211142Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:24:51.148692001Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:25:51.668112986Z"}
{"log":"[FATAL tini (8)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:26:52.158669222Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:27:52.644273035Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:27:56.999283799Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:27:57.641752262Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:27:58.594551969Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:27:59.487705249Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:28:00.812679532Z"}
{"log":"[FATAL tini (8)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:28:02.889828969Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:28:06.577079756Z"}
{"log":"[FATAL tini (7)] exec /bin/sh failed: Exec format error\r\n","stream":"stdout","time":"2024-08-27T03:28:13.473355321Z"}
```

**Comment by wangzul** [comment]
没替换secretpad.jar前SecretPad是否可以正常运行？
如果需要二次开发的话建议参照文档来https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.9.0b0/development/ru_in_idea_cn#secretpad-java

一般情况下/bin/sh 时遇到了“Exec format error”这通常意味着尝试执行的二进制文件与操作系统的期望格式不兼容，比如 在X86架构运行arm架构的二进制文件。你可以检查一下当前的环境。

**Comment by wangzeyu135798** [comment]
没替换secretpad.jar之前容器是可以运行的。
我本地是按照 https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.6.0b0/development/ru_in_idea_cn 这个方式编译的代码，且可以本地正常启动secretpad
我本地编译启动secretpad代码的机器架构和运行容器的机器架构均为x86
![image](https://github.com/user-attachments/assets/77878008-4dcd-4bca-a022-c4f1e91f557c)
![Uploading image.png…]()

**Comment by wangzul** [comment]
可以说一下你这个日志文件是在哪里查看的吗？或者是查看命令。

**Comment by wangzeyu135798** [comment]
sudo docker inspect containerID
查看LogPath路径的日志内容

**Comment by wangzul** [comment]
容器有在运行吗？docker ps看一下,如果pad容器正常运行
1. docker logs -f --tail=100 容器名称
2.可以进入容器内部docker exec -it 容器名称 bash 查看一下/app/log/下的日志文件。

**Comment by wangzeyu135798** [comment]
容器一直是restarting的状态，进入不到容器内部
docker logs -f --tail=100 容器名称
![86a84beaba3466d7fefb7f5ca6f5c491](https://github.com/user-attachments/assets/70fa2fad-8ac5-41f2-92ce-683bb0717317)

**Comment by wangzul** [comment]
> 容器一直是restarting的状态，进入不到容器内部 docker logs -f --tail=100 容器名称 ![86a84beaba3466d7fefb7f5ca6f5c491](https://private-user-images.githubusercontent.com/39690172/361698978-70fa2fad-8ac5-41f2-92ce-683bb0717317.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDQyMjEsIm5iZiI6MTcyNDc0MzkyMSwicGF0aCI6Ii8zOTY5MDE3Mi8zNjE2OTg5NzgtNzBmYTJmYWQtOGFjNS00MWYyLTkyY2UtNjgzYmIwNzE3MzE3LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA3MzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMzM3YTNlNDAwYzE4Mzk2OWM1MTY4ZGI3ZTk1MzA2YzFiMjk2ODFhMDQ3NjU1YWVjNGFiYWNjMzNmNzU2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3tCZ1Fs9g-cV_COoJ-ykZJ5uIoIej1ME1L27BKLmVEw)

docker inspect  pad容器 查看一下挂载日志的目录
"Mounts": [
            {
                "Type": "bind",
                "Source": "/root/kuscia/autonomy/secretpad/alice-latest/log",
                "Destination": "/app/log",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
        ],
然后提供一下修改jar前后时间的error.log

**Comment by wangzeyu135798** [comment]
我的error.log 好像没有修改jar时间前后的错误信息
![f120bb8cfc4d988658ca8f44ea940ef7](https://github.com/user-attachments/assets/86262dc9-f65b-410b-ba5c-b45043bacd91)
![5102cf3ee5870aa432c081fda7cbe651](https://github.com/user-attachments/assets/f28fb8b4-c735-43d6-8c3a-b261753c9e7f)
![Uploading 651f3d85be689d87b8eb765c3bf37254.JPG…]()

**Comment by wangzeyu135798** [comment]
![Uploading 3099800c1d197a37a436107ae87a5ed6.JPG…]()
启动容器后，这两个文件也没有重新生成，是不是因为容易没有成功启动的缘故？

**Comment by wangzul** [comment]
docker inspect -f '{{ .Architecture }}'  镜像名称  输入docker ps 中pad容器的image信息。
同时再次确认一下是否只是编译了pad后替换了原有的容器pad.jar
