### ISSUE TITLE
如何将业务数据转成合理的训练数据 

### ISSUE THREAD

**Issue by EightMonth** [secretflow/secretpad#124]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Link to Relevant Documentation

https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.8.0b0/center_deploy/method1

### Question Details

```shell
不知道如何去将业务数据转成合理的训练数据。
现有的业务数据全是中文的，如下：
id,name,gender,age,married
1,张三,男，24,false
2,李四,女,34,true

不过我看训练算法组件都是接受的double类型的值，我应该如何将以上数据转成训练算法可接受的数据。

另外再想问的一点就是，我看文档中模型发布后示例调的结果的scores代表的含义是什么
https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.6.0b0/tutorial/run_sf_serving_with_api_cn#id5
```

**Comment by zimu-yuxi** [comment]
1.可以支持多种类型的。如果想要做转换，可以使用交叉决策组件，比如把gender转换成0/1
2.预测的分数，可以参考[此处](https://www.secretflow.org.cn/zh-CN/docs/serving/0.6.0b0/reference/api#predictresult)

**Comment by EightMonth** [comment]
2中回复的文档早已看过了，不过还不太明白0.75代表的是什么意思 0.25又是什么意思

**Comment by zimu-yuxi** [comment]
模型预测值
