### ISSUE TITLE
重新构建pad编译文档的时候报错

### ISSUE THREAD

**Issue by Handikang** [secretflow/secretpad#13]
![image](https://github.com/secretflow/secretpad/assets/42713276/e5448f9b-6f5f-45bb-9cca-714501961136)

![image](https://github.com/secretflow/secretpad/assets/42713276/2ebbf1c0-a7d0-4367-95cd-ae36a8d1b46f)

**Comment by xiushuiguande** [comment]
hi，我们复现一下

**Comment by xiushuiguande** [comment]
![image](https://github.com/secretflow/secretpad/assets/34685731/245e1ea7-6ca6-4fed-96ec-cbc1879f1c05)
尝试pip安装一下Sphinx==1.1.3试下

**Comment by Handikang** [comment]
@xiushuiguande 你好，这个问题已经解决了，我换了个python环境,就可以了，是环境依赖问题

**Comment by jack-ming** [comment]
> @xiushuiguande 你好，这个问题已经解决了，我换了个python环境,就可以了，是环境依赖问题

你好，是使用的python哪个版本呢，我这不同版本遇到不同的错误

**Comment by Chrisdehe** [comment]
@jack-ming 你好，python==3.8版本即可
