### ISSUE TITLE
allinone部署方式的问题

### ISSUE THREAD

**Issue by ShaneGu4Real** [secretflow/secretpad#133]
### Issue Type

Api Usage

### Have you searched for existing issues?

Yes

### Question Details

```shell
如果我们想部署secretpad all in one，因为我看教程里是直接在Linux/Mac环境里执行shell脚本把容器拉起来，可否将全家桶部署在云环境里，比如k8s里，或者还支持其他什么部署方式，部署secretpad、kuscia等全家桶，如果可以应该怎么做。
```

**Comment by 383004576** [comment]
allinone暂时没有其他部署脚本。
kuscia部署参考：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/K8s_deployment_kuscia
secretpad可以参考本地调试模式，自行调试脚本：https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.9.0b0/development/ru_in_idea_cn

**Comment by ShaneGu4Real** [comment]
kuscia在k8s集群里部署过，我理解的是否是 allinone没法在k8s集群里部署呢？

**Comment by 383004576** [comment]
是的allinone没法在直接在k8s集群部署

**Comment by ShaneGu4Real** [comment]
谢谢

**Comment by ShaneGu4Real** [comment]
您好，我们现在的诉求是希望部署在云环境里，但是云资源环境都是k8s的，是需要申请裸主机或者Linux虚拟环境才可以部署吗，想问下，如果allinone没法在k8s集群里部署，有其他什么方式可以部署在云环境里吗

**Comment by zimu-yuxi** [comment]
> 您好，我们现在的诉求是希望部署在云环境里，但是云资源环境都是k8s的，是需要申请裸主机或者Linux虚拟环境才可以部署吗，想问下，如果allinone没法在k8s集群里部署，有其他什么方式可以部署在云环境里吗

目前allinone部署包中的install.sh脚本不支持在k8s部署（目前仅支持docker部署）。allinone包其实就是部署secretpad和kuscia容器，你可以在k8s中分别部署secretpad和kuscia
