### ISSUE TITLE
二次开发，创建项目工作流时报权限错误

### ISSUE THREAD

**Issue by wangzeyu135798** [secretflow/secretpad#137]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

centos7

### All_in_one Version

0.6

### Kuscia Version

0.7

### What happend and What you expected to happen.

```shell
调用接口/api/v1alpha1/graph/create时，报下面错误：
{
    "status": {
        "code": 202011602,
        "msg": "用户认证失败: No permission to access the data PROJECT_ID(lrhrbjrg). owner_type(P2P), owner_id(alice)"
    },
    "data": null
}
```

### Log output.

```shell
{
    "status": {
        "code": 202011602,
        "msg": "用户认证失败: No permission to access the data PROJECT_ID(lrhrbjrg). owner_type(P2P), owner_id(alice)"
    },
    "data": null
}
```

**Comment by wangzeyu135798** [comment]
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/e94b6197-9250-47e1-a963-84d56163f13d">
创建project是本方节点调用上面的代码，合作方节点调用接口/api/v1alpha1/message/reply。

**Comment by zimu-yuxi** [comment]
自定义的controller中request少传参数
