### ISSUE TITLE
替换secretpad前端之后，点击组件，会跳转到不存在的接口

### ISSUE THREAD

**Issue by wangzeyu135798** [secretflow/secretpad#138]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

centos7

### All_in_one Version

0.6

### Kuscia Version

0.7

### What happend and What you expected to happen.

```shell
在secretpad里面，我替换了一下前端代码，前端代码的修改并不涉及项目等内容，但是我进入到工作流点击具体组件的时候，就会报404的错误，我看了secretpad后端代码本来就没有这个接口，请问这是什么原因？
```

### Log output.

```shell
none
```

**Comment by wangzeyu135798** [comment]
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/2f394852-031d-4ae1-bde8-640f91c891c2">

**Comment by wangzul** [comment]
> <img alt="image" width="1303" src="https://private-user-images.githubusercontent.com/39690172/365961663-2f394852-031d-4ae1-bde8-640f91c891c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjE2ODQsIm5iZiI6MTcyNTk2MTM4NCwicGF0aCI6Ii8zOTY5MDE3Mi8zNjU5NjE2NjMtMmYzOTQ4NTItMDMxZC00YWUxLWJkZTgtNjQwZjkxYzg5MWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA5NDMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZTQ5MmM5YWU2NTE5NTJmZDEyMDY5Yjk1YjRlNzBkNjBkNzM4N2U2OWUyMTVjNDFmMWY5OWM5NTAwMDAyNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UAMVRJMiDEEZ970F_C2zcq3d35FvSvhNhedGcY_Ou5c">

1. 后端接口路径 src/main/java/org/secretflow/secretpad/web/controller/CloudLogController.java 你可以检查一下你的pad代码并提供一下你的pad版本。
2. 确认一下你的pad的端口是8089吗

**Comment by wangzeyu135798** [comment]
我的后端是0.6.0b0版本，没有cloud_log/sls接口；端口是8089。所以是不是前端的版本不匹配？

**Comment by wangzul** [comment]
> 我的后端是0.6.0b0版本，没有cloud_log/sls接口；端口是8089。所以是不是前端的版本不匹配？



> > 我的后端是0.6.0b0版本，没有cloud_log/sls接口；端口是8089。所以是不是前端的版本不匹配？
> 
> ![image](https://private-user-images.githubusercontent.com/55971198/366015076-69926560-1fbf-4e70-a041-869026d9cd64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjY5MjAsIm5iZiI6MTcyNTk2NjYyMCwicGF0aCI6Ii81NTk3MTE5OC8zNjYwMTUwNzYtNjk5MjY1NjAtMWZiZi00ZTcwLWEwNDEtODY5MDI2ZDljZDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDExMTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkM2VlNmFjOWNhZjQ0MGMzMjRkZTYwYTYxYmQ4NTJhMDE4MDVjOWJjY2IwZjYwZDNlMzYyMjJlZDEzNWE5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sr7epxxQDBk56lT-PJc6MgrRSPKad_A-7LEip9oSOjA) 前端代码你可通过这种方式获取

https://github.com/secretflow/secretpad/blob/v0.6.0b0/README.zh-CN.md

**Comment by wangzeyu135798** [comment]
在https://github.com/secretflow/secretpad-frontend/tree/v0.6.0b0下载的前端启动后如下图所示，为什么页面内容和all in one模式下启动的前端页面不一样？

**Comment by wangzeyu135798** [comment]
![4acfd2bf90f6d370d026e9d5ebb712d](https://github.com/user-attachments/assets/12f8ead3-153d-4924-aabd-fe9d948fde7d)

**Comment by wangzul** [comment]
> <img alt="image" width="1674" src="https://private-user-images.githubusercontent.com/39690172/366036796-f492a702-c5c6-4d73-bf81-e658b8067c59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjA0MTUsIm5iZiI6MTcyNjAyMDExNSwicGF0aCI6Ii8zOTY5MDE3Mi8zNjYwMzY3OTYtZjQ5MmE3MDItYzVjNi00ZDczLWJmODEtZTY1OGI4MDY3YzU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAyMDE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4M2ZmNWFhOWQxMGMxYzE1MGFkN2U2YTQ1MzRiNTUzMWJiOTBiMzRmZWJlZTlkMTlmZTEwODhkMGQ4ZTJkZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XXtQSvefTWdOqkRM87pqu0KJMiaGsVejdJz65uBGsaE"> 这个是all in one 模式下0.6版本的前端页面

1. 第一种如果是镜像启动需要配置docker run -e SPRING_PROFILES_ACTIVE=p2p   
2. 第二种方法修改配置文件中  platform-type: AUTONOMY

部署参考https://secretflow.github.io/secretpad-frontend/dev-doc/build

**Comment by liusiqqq** [comment]
大佬，你后端代码是在哪个系统上运行的

**Comment by zimu-yuxi** [comment]
已解决。secretpad版本和前端版本不对应。前端代码拉取的是main代码，没有checkout
