### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by Chiliad-Spring** [secretflow/secretpad#141]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

Ubuntu 20.04

### All_in_one Version

v1.9.0

### Module type

secretpad

### Module version

0.10.0b0/0.10.1b0

### What happend and What you expected to happen.

```shell
when run the ./install.sh master
It seems like the sed command cant  analyze multiple lines of code
such as 
sed "s|{{.TEE_NODE_NAME}}|${TEE_NODE_NAME}|g;
  s|{{.TEE_CAPSULE_MANAGER_SIM_IMAGE}}|${CAPSULE_MANAGER_SIM_IMAGE}|g" \
                tee-capsule-manager.yaml >tee-capsule-manager-0.yaml

How to solve it?
```

### Log output.

```shell
[INFO] Image 'secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/capsule-manager-sim-ubuntu20.04:v0.1.0b0' already exists in domain 'root-kuscia-lite-tee'
+ return
+ init_tee
+ log 'start init tee crd'
+ echo -e '\033[0;34m[INFO]\033[0m start init tee crd'
[INFO] start init tee crd
++ pwd
+ docker run --rm --entrypoint /bin/bash -v /root/secretflow-allinone-package:/tmp/secretpad secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretpad:0.9.0b0 -c 'cp -R /app/scripts/templates/tee-image.yaml /tmp/secretpad/'
++ pwd
+ docker run --rm --entrypoint /bin/bash -v /root/secretflow-allinone-package:/tmp/secretpad secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretpad:0.9.0b0 -c 'cp -R /app/scripts/templates/tee-capsule-manager.yaml /tmp/secretpad/'
++ docker exec -it root-kuscia-master kubectl get nodes
++ grep tee
++ awk '{print $1}'
+ TEE_NODE_NAME='root-kuscia-lite-alice-tee-node34
root-kuscia-lite-bob-tee-node34
root-kuscia-lite-tee-tee-node34'
+ sed 's|{{.TEE_NODE_NAME}}|root-kuscia-lite-alice-tee-node34
root-kuscia-lite-bob-tee-node34
root-kuscia-lite-tee-tee-node34|g;
  s|{{.TEE_CAPSULE_MANAGER_SIM_IMAGE}}|secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/capsule-manager-sim-ubuntu20.04:v0.1.0b0|g' tee-capsule-manager.yaml
sed: -e expression #1, char 54: unterminated `s' command
```

**Comment by john8628** [comment]
please see your docker version , please follow the doc [docker version ](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/deploy_check#docker)

**Comment by Chiliad-Spring** [comment]
> please see your docker version , please follow the doc [docker version ](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/deploy_check#docker)

My Docker version 20.10.24, build 297e128
Maybe not this , something was wrong with the "sed" command

**Comment by 1139763082** [comment]
> ### Issue Type
> Install/Deploy
> 
> ### Have you searched for existing documents and issues?
> Yes
> 
> ### OS Platform and Distribution
> Ubuntu 20.04
> 
> ### All_in_one Version
> v1.9.0
> 
> ### Module type
> secretpad
> 
> ### Module version
> 0.10.0b0/0.10.1b0
> 
> ### What happend and What you expected to happen.
> ```shell
> when run the ./install.sh master
> It seems like the sed command cant  analyze multiple lines of code
> such as 
> sed "s|{{.TEE_NODE_NAME}}|${TEE_NODE_NAME}|g;
>   s|{{.TEE_CAPSULE_MANAGER_SIM_IMAGE}}|${CAPSULE_MANAGER_SIM_IMAGE}|g" \
>                 tee-capsule-manager.yaml >tee-capsule-manager-0.yaml
> 
> How to solve it?
> ```
> 
> ### Log output.
> ```shell
> [INFO] Image 'secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/capsule-manager-sim-ubuntu20.04:v0.1.0b0' already exists in domain 'root-kuscia-lite-tee'
> + return
> + init_tee
> + log 'start init tee crd'
> + echo -e '\033[0;34m[INFO]\033[0m start init tee crd'
> [INFO] start init tee crd
> ++ pwd
> + docker run --rm --entrypoint /bin/bash -v /root/secretflow-allinone-package:/tmp/secretpad secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretpad:0.9.0b0 -c 'cp -R /app/scripts/templates/tee-image.yaml /tmp/secretpad/'
> ++ pwd
> + docker run --rm --entrypoint /bin/bash -v /root/secretflow-allinone-package:/tmp/secretpad secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretpad:0.9.0b0 -c 'cp -R /app/scripts/templates/tee-capsule-manager.yaml /tmp/secretpad/'
> ++ docker exec -it root-kuscia-master kubectl get nodes
> ++ grep tee
> ++ awk '{print $1}'
> + TEE_NODE_NAME='root-kuscia-lite-alice-tee-node34
> root-kuscia-lite-bob-tee-node34
> root-kuscia-lite-tee-tee-node34'
> + sed 's|{{.TEE_NODE_NAME}}|root-kuscia-lite-alice-tee-node34
> root-kuscia-lite-bob-tee-node34
> root-kuscia-lite-tee-tee-node34|g;
>   s|{{.TEE_CAPSULE_MANAGER_SIM_IMAGE}}|secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/capsule-manager-sim-ubuntu20.04:v0.1.0b0|g' tee-capsule-manager.yaml
> sed: -e expression #1, char 54: unterminated `s' command
> ```

You execute 'docker ps' to see what container is running
