### ISSUE TITLE
引擎日志可以在哪里查看

### ISSUE THREAD

**Issue by EightMonth** [secretflow/secretpad#143]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
不知道哪个日志文件中的日志属于secretpad界面中的引擎日志
```

**Comment by Chrisdehe** [comment]
在这里～
https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/logdescription

**Comment by EightMonth** [comment]
这么多日志文件是都会综合到secretpad的引擎日志窗口去显示的么，还是具体的某一个

**Comment by zimu-yuxi** [comment]
> 这么多日志文件是都会综合到secretpad的引擎日志窗口去显示的么，还是具体的某一个

标准日志输出（stdout）下的日志，也就是任务执行日志

**Comment by EightMonth** [comment]
我看阿里云SLS目前只能接阿里云的云服务器，如果secretpad部署在自建机器上，就始终无法通过界面查看引擎日志了，这个有招么

**Comment by zimu-yuxi** [comment]
> ![3832dadcac7f2ab9cea1f972ff12d1e](https://private-user-images.githubusercontent.com/23272421/368453175-ebce9e85-f65b-4310-b264-7c9314277b45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ3MjMsIm5iZiI6MTcyNjY0NDQyMywicGF0aCI6Ii8yMzI3MjQyMS8zNjg0NTMxNzUtZWJjZTllODUtZjY1Yi00MzEwLWIyNjQtN2M5MzE0Mjc3YjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3MjcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMWE3NDA0YjJlMTNmOWM0ZDA1NWRmYmUxNjc1ZWI2MGFkMTRjMjFmZWY1NWY4ZTAwNjZlYzJlNTBkN2FiMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F6cNOqxpyxkIGtZsLUpfUFUwD51pS9QgVnIDgNGuNnA) kuscia内的http请求日志，发出的请求跟接收的请求都有body长度，但是日志没有记录body内容，请问这个body内容在哪里看呢

最新版本有kusciaAPI.log，可以看下

**Comment by zimu-yuxi** [comment]
> 我看阿里云SLS目前只能接阿里云的云服务器，如果secretpad部署在自建机器上，就始终无法通过界面查看引擎日志了，这个有招么

可以看下[这里](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.10.1b0/development/support_sls_cloud_log)

**Comment by EightMonth** [comment]
> > 我看阿里云SLS目前只能接阿里云的云服务器，如果secretpad部署在自建机器上，就始终无法通过界面查看引擎日志了，这个有招么
> 
> 可以看下[这里](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.10.1b0/development/support_sls_cloud_log)

这个在安装logtail时，如果不是阿里云的机器 就会无法上传日志文件，之前已经试过了

**Comment by zimu-yuxi** [comment]
可以暂时先在容器内部查看日志
