### ISSUE TITLE
进行项目训练执行时出现错误，隐私求交失败

### ISSUE THREAD

**Issue by Linux-YANGFF** [secretflow/secretpad#146]
### Issue Type

Running

### Have you searched for existing documents and issues?

No

### OS Platform and Distribution

centos 8

### All_in_one Version

v1.8.0

### Module type

secretflow

### Module version

v1.8.0.b0

### What happend and What you expected to happen.

```shell
在进行合作节点建立连接后，创建了一个项目，进行数据的测试训练。样本集都是简单的key-value类型的，两个样本集进行隐私求交，求交失败了
```

### Log output.

```shell
2024-09-19 17:47:54 INFO the jobId=ymak, taskId=ymak-mciasgwx-node-40 failed: party alice failed msg: container[secretflow] terminated state reason "Error", message: "WARNING:root:Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.
Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/runpy.py\", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File \"/usr/local/lib/python3.10/runpy.py\", line 86, in _run_code
    exec(code, run_globals)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\", line 551, in <module>
    main()
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1157, in __call__
    return self.main(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1078, in main
    rv = self.invoke(ctx)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 783, in invoke
    return __callback(*args, **kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\", line 506, in main
    datasource = get_domain_data_source(datasource_stub, datasource_id)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/datamesh.py\", line 115, in get_domain_data_source
    raise RuntimeError(f\"get_domain_data_source failed for {id}: ret = {ret}\")
RuntimeError: get_domain_data_source failed for default-data-source: ret = status {
  code: 12302
  message: \"decrypt data source info failed, crypto/rsa: decryption error\"
}
```

**Comment by Linux-YANGFF** [comment]
数据集：
[test2.xlsx](https://github.com/user-attachments/files/17068542/test2.xlsx)

组件：
![image](https://github.com/user-attachments/assets/6411cb2a-852f-40d6-9464-6666af10637c)

**Comment by lanyy9527** [comment]
decrypt data source info failed, crypto/rsa: decryption error
这个报错一般是 节点重装后节点的私钥变了，导致无法解密之前的数据; 节点重装如果希望保留原有数据，需要保留节点的私钥 （kuscia.yaml 中的 domainkey字段 即为私钥）

**Comment by Linux-YANGFF** [comment]
> decrypt data source info failed, crypto/rsa: decryption error 这个报错一般是 节点重装后节点的私钥变了，导致无法解密之前的数据; 节点重装如果希望保留原有数据，需要保留节点的私钥 （kuscia.yaml 中的 domainkey字段 即为私钥）

![image](https://github.com/user-attachments/assets/670de5c1-1b6d-448a-919a-b6ca9986cae9)
这是我的配置，之前确实重新安装过all in one，现在需要怎么操作，在kuscia.yaml文件添加domainkey字段吗

**Comment by Linux-YANGFF** [comment]
我这个是重装之后，在进行数据集导入的（而不是导入数据集之后再进行重装），按理说之前的密钥应该不会影响

**Comment by lanyy9527** [comment]
> 我这个是重装之后，在进行数据集导入的（而不是导入数据集之后再进行重装），按理说之前的密钥应该不会影响

清理下kusica的缓存，删除ls /${USER}/kuscia后，再重装

**Comment by Linux-YANGFF** [comment]
> > 我这个是重装之后，在进行数据集导入的（而不是导入数据集之后再进行重装），按理说之前的密钥应该不会影响
> 
> 清理下kusica的缓存，删除ls /${USER}/kuscia后，再重装

两台都需要重新安装吗

**Comment by lanyy9527** [comment]
> > > 我这个是重装之后，在进行数据集导入的（而不是导入数据集之后再进行重装），按理说之前的密钥应该不会影响
> > 
> > 
> > 清理下kusica的缓存，删除ls /${USER}/kuscia后，再重装
> 
> 两台都需要重新安装吗

是的
