### ISSUE TITLE
本地启动两个secrecpad实列，添加通信节点报错

### ISSUE THREAD

**Issue by 123zzc** [secretflow/secretpad#148]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

centos

### All_in_one Version

0.6.0

### Kuscia Version

0.7.0

### What happend and What you expected to happen.

```shell
远程以p2p模式启动了两个kuscia实列，本地两个secretpad实列。添加合作节点时状态不可用。
```

### Log output.

```shell
2024-09-29 11:01:26.461 ERROR controller/domain_route.go:296 response status code [503], detail -> upstream connect error or disconnect/reset before headers. reset reason: connection termination
2024-09-29 11:01:26.461 INFO queue/queue.go:109 Re-syncing: queue id[domain-route-queue], retry:[12] key[rxf/rxf-zhaohang2]: "response status code [503], detail -> upstream connect error or disconnect/reset before headers. reset reason: connection termination", re-queuing (5.014163086s)
```

**Comment by 123zzc** [comment]
<img width="276" alt="1727578829807" src="https://github.com/user-attachments/assets/f1a58511-6c71-4ee7-abf7-e3dc1bbc63e8">
<img width="1154" alt="1727579106120" src="https://github.com/user-attachments/assets/8a3a45bf-c577-4099-8c60-e8409c1da68f">

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo

Password: changeme
I put the necessary dlls in the archive

**Comment by 123zzc** [comment]
<img width="1162" alt="1727579359554" src="https://github.com/user-attachments/assets/e2663f1f-becc-488d-9956-5c832de052be">

**Comment by 123zzc** [comment]
本地配置文件：
<img width="382" alt="1727580800821" src="https://github.com/user-attachments/assets/46fbce3f-c16d-4670-9974-5890777f403e">

**Comment by zhouming666-coder** [comment]
需要确认您创建节点采用的是NOTLS、MTLS、TLS模式
![截屏2024-09-29 15 20 56](https://github.com/user-attachments/assets/30258529-b54a-47d7-b219-a07d128ba26d)

**Comment by 123zzc** [comment]
![b9dc2d30ed91f771ee89554e0cbc851](https://github.com/user-attachments/assets/88dd1bfd-523a-4981-9a2c-a8c5b669fd7c)

**Comment by 123zzc** [comment]
<img width="338" alt="1727595343145" src="https://github.com/user-attachments/assets/e01d4375-2dbc-424c-bb52-87373bf223e3"> 已经改成https了 还是不行

**Comment by 123zzc** [comment]
<img width="570" alt="1727596350656" src="https://github.com/user-attachments/assets/2367237c-3dea-4331-b5f6-392051c2fe08">
授权状态信息

**Comment by zhouming666-coder** [comment]
确认您是否两边通信节点都是https，添加的时候都需要匹配。

**Comment by 123zzc** [comment]
> 确认您是否两边通信节点都是https，添加的时候都需要匹配。

是的两边都是https

**Comment by 123zzc** [comment]
路由状态如下：
<img width="850" alt="1727601617256" src="https://github.com/user-attachments/assets/8f6e4e15-ef34-4e05-ba9c-6a26548764b5">

**Comment by 123zzc** [comment]
两个节点都加上才能建立成功
