### ISSUE TITLE
使用make pack的包执行隐私求交报错

### ISSUE THREAD

**Issue by hlysf** [secretflow/secretpad#15]
![image](https://github.com/secretflow/secretpad/assets/66900073/8c6398b4-7455-42cd-81dc-efc247ea65ad)

**Comment by CodePorterL** [comment]
@hlysf 麻烦执行一下`uname -a` 看一下输出内容

**Comment by hlysf** [comment]
> @hlysf 麻烦执行一下`uname -a` 看一下输出内容

Linux  #1 SMP Wed Jun 10 09:04:49 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 6fj** [comment]
可以用下面的cmd检查一下，如果没有输出则说明你的机器不支持avx。

```
cat /proc/cpuinfo | grep avx
```

**Comment by hlysf** [comment]
> 可以用下面的cmd检查一下，如果没有输出则说明你的机器不支持avx。
> 
> ```
> cat /proc/cpuinfo | grep avx
> ```

确实没有输出。谢谢你的解答~

**Comment by anakinxc** [comment]
> > 可以用下面的cmd检查一下，如果没有输出则说明你的机器不支持avx。
> > ```
> > cat /proc/cpuinfo | grep avx
> > ```
> 
> 确实没有输出。谢谢你的解答~

Hi @hlysf 

能提供一下 cpu 的信息吗？

Thx

**Comment by hlysf** [comment]
> > > 可以用下面的cmd检查一下，如果没有输出则说明你的机器不支持avx。
> > > ```
> > > cat /proc/cpuinfo | grep avx
> > > ```
> > 
> > 
> > 确实没有输出。谢谢你的解答~
> 
> Hi @hlysf
> 
> 能提供一下 cpu 的信息吗？
> 
> Thx

![image](https://github.com/secretflow/secretpad/assets/66900073/25b93c3f-78dc-4669-b183-956b61c10a72)
