### ISSUE TITLE
本地开发secretpad，在合作节点建立成功的前提下下，建立合作项目对方接受不到

### ISSUE THREAD

**Issue by 123zzc** [secretflow/secretpad#150]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

centos

### All_in_one Version

0.6.0

### Module type

secretpad

### Module version

0.6.0

### What happend and What you expected to happen.

```shell
本地开发secretpad，在合作节点建立成功的前提下下，建立合作项目对方接受不到
```

### Log output.

```shell
无
```

**Comment by 123zzc** [comment]
<img width="1031" alt="1728455869327" src="https://github.com/user-attachments/assets/c25dbfa1-58b8-49a8-ac49-1d8b236a12d5">
节点通信成功
<img width="428" alt="1728455921506" src="https://github.com/user-attachments/assets/622fe431-cd42-41bc-a506-a3730497f7dd">
<img width="482" alt="1728455941610" src="https://github.com/user-attachments/assets/a2c52f47-e15b-444c-9b1e-0a52f3c0690a">
对方无反义。

发起方发起vote请求成功：
<img width="1021" alt="1728455997589" src="https://github.com/user-attachments/assets/7af90a65-c432-4105-8e80-be44f20f3fbc">

**Comment by zimu-yuxi** [comment]
双方secretpad都是在本地启动的吗？版本是多少

**Comment by 123zzc** [comment]
> 双方secretpad都是在本地启动的吗？版本是多少

都是本地启动。版本号为0.10.b0，kuscia版本为0.11.0b0。

这是对应配置文件：
<img width="365" alt="1728461770127" src="https://github.com/user-attachments/assets/def115a6-8124-4941-95aa-e3a195faeabe">

**Comment by zimu-yuxi** [comment]
1.secretpad容器里看下sync-data.log日志，看下是否有报错信息，猜测可能会有503
2.进kuscia容器里，kubectl get svc看下

**Comment by 123zzc** [comment]
<img width="746" alt="1728462597285" src="https://github.com/user-attachments/assets/55b2a77a-f8a1-4510-8333-e4111c68ff58">
<img width="164" alt="1728462620656" src="https://github.com/user-attachments/assets/06c805b5-e4fe-40c7-baff-c1e1e21232d1">

应该是网关配置问题，请问这个网关和kuscia端口有关吗。如果没有我改如何设置。

**Comment by zimu-yuxi** [comment]
这里是secretpad的数据同步端口。docker ps看一下

**Comment by 123zzc** [comment]
没用docker启动，是windows本地启动的。

**Comment by zimu-yuxi** [comment]
可以参考[这里](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.10.1b0/development/ru_in_idea_cn#id14)看下如何配置

**Comment by zimu-yuxi** [comment]
方便进kuscia容器里kubectl get svc看下吗？感谢

**Comment by 123zzc** [comment]
> 方便进kuscia容器里kubectl get svc看下吗？感谢

因为是windows本地启动，并没有使用容器。 将gateway改成对方http-port-inner后解决了。

**Comment by zimu-yuxi** [comment]
kuscia你们也是本地启动的吗？没有使用镜像吗？

**Comment by 123zzc** [comment]
> kuscia你们也是本地启动的吗？没有使用镜像吗？
理解错了 我以为您说是secretpad。
![1728463837401](https://github.com/user-attachments/assets/9d67ed4a-38de-40e4-b113-4dd9620ac988)

**Comment by zimu-yuxi** [comment]
> > kuscia你们也是本地启动的吗？没有使用镜像吗？
> > 理解错了 我以为您说是secretpad。
> > ![1728463837401](https://private-user-images.githubusercontent.com/25130362/374881879-9d67ed4a-38de-40e4-b113-4dd9620ac988.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjQxNDksIm5iZiI6MTcyODQ2Mzg0OSwicGF0aCI6Ii8yNTEzMDM2Mi8zNzQ4ODE4NzktOWQ2N2VkNGEtMzhkZS00MGU0LWIxMTMtNGRkOTYyMGFjOTg4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA4NTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYzkxMmI3YjE0MTMwYWIyM2JkOGJhMzEzMDkyOTIwZTMyY2ZmMmNmYmZhYjZkZjI1ZDVkNzU1Y2I3NTZjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.INNszqRqAQeu9neNndRzR_p5m1dbd4LZWmnyJKL9xeY)

好的，感谢！！

**Comment by anyejunwang** [comment]
> > 方便进kuscia容器里kubectl get svc看下吗？感谢
> 
> 因为是windows本地启动，并没有使用容器。 将gateway改成对方http-port-inner后解决了。

老师，请问一下，如果按照如此配置的方式，那是否意味着我们现在p2p模式下面一台secretPad只能支持一对一的节点训练（因为getway这里写死了对方的IP和http-port-inner），若想实现一个secretPad对接多个节点，请问需要如何实现

**Comment by anyejunwang** [comment]
> kubectl get svc -A

![image](https://github.com/user-attachments/assets/51de8fc5-1e74-44ff-a2b9-7f9dae6c88cb)
zh这个是当前命令执行后的截图

**Comment by zimu-yuxi** [comment]
大概确认了，你可以在kuscia容器新建一个service，secretpad的service。正常secretpad的数据同步是借助kuscia的网络进行的，比如alice的secretpad->alice的kuscia->bob的kuscia->bob的secretpad。然后你的secretpad的gateway换成本方的kuscia的IP和gataway端口，就可以对接多个节点，只要双方kuscia的路由正常建立

**Comment by anyejunwang** [comment]
> 大概确认了，你可以在kuscia容器新建一个service，secretpad的service。正常secretpad的数据同步是借助kuscia的网络进行的，比如alice的secretpad->alice的kuscia->bob的kuscia->bob的secretpad。然后你的secretpad的gateway换成本方的kuscia的IP和gataway端口，就可以对接多个节点，只要双方kuscia的路由正常建立

老师，我们还没有咨询您的时候，secretpad的gateway填写的就是本方的kuscia的IP和启动时候-p指定的端口（即getway端口），但是这种配置，双方节点建立连接是可以成功并显示生效的，但是建立项目的时候无法推送给对方审批

**Comment by zimu-yuxi** [comment]
嗯，明白，因此需要在kuscia容器里配置secrtpad的service，这个service其实就是k3s的service。你可以使用我们的allinone包部署，然后去kuscia容器里kubectl get svc -A看下会有一个secretpad的service。

**Comment by wangzul** [comment]
> > 大概确认了，你可以在kuscia容器新建一个service，secretpad的service。正常secretpad的数据同步是借助kuscia的网络进行的，比如alice的secretpad->alice的kuscia->bob的kuscia->bob的secretpad。然后你的secretpad的gateway换成本方的kuscia的IP和gataway端口，就可以对接多个节点，只要双方kuscia的路由正常建立
> 
> 老师，我们还没有咨询您的时候，secretpad的gateway填写的就是本方的kuscia的IP和启动时候-p指定的端口（即getway端口），但是这种配置，双方节点建立连接是可以成功并显示生效的，但是建立项目的时候无法推送给对方审批

可以在kuscia节点中执行下方脚本，这个脚本会创建secrtpad  service

bash scripts/deploy/create_secretpad_svc.sh [pad-ip] [domainId]

**Comment by wangzul** [comment]
> > 大概确认了，你可以在kuscia容器新建一个service，secretpad的service。正常secretpad的数据同步是借助kuscia的网络进行的，比如alice的secretpad->alice的kuscia->bob的kuscia->bob的secretpad。然后你的secretpad的gateway换成本方的kuscia的IP和gataway端口，就可以对接多个节点，只要双方kuscia的路由正常建立
> 
> 老师，我们还没有咨询您的时候，secretpad的gateway填写的就是本方的kuscia的IP和启动时候-p指定的端口（即getway端口），但是这种配置，双方节点建立连接是可以成功并显示生效的，但是建立项目的时候无法推送给对方审批

可以在kuscia节点中执行下方脚本，这个脚本会创建secrtpad  service

bash scripts/deploy/create_secretpad_svc.sh [pad-ip:默认端口9001] [domainId]

**Comment by anyejunwang** [comment]
> > > 大概确认了，你可以在kuscia容器新建一个service，secretpad的service。正常secretpad的数据同步是借助kuscia的网络进行的，比如alice的secretpad->alice的kuscia->bob的kuscia->bob的secretpad。然后你的secretpad的gateway换成本方的kuscia的IP和gataway端口，就可以对接多个节点，只要双方kuscia的路由正常建立
> > 
> > 
> > 老师，我们还没有咨询您的时候，secretpad的gateway填写的就是本方的kuscia的IP和启动时候-p指定的端口（即getway端口），但是这种配置，双方节点建立连接是可以成功并显示生效的，但是建立项目的时候无法推送给对方审批
> 
> 可以在kuscia节点中执行下方脚本，这个脚本会创建secrtpad service
> 
> bash scripts/deploy/create_secretpad_svc.sh [pad-ip:默认端口9001] [domainId]

好的，谢谢老师，我们明天调整一下，非常感谢

**Comment by gxcuit** [comment]
@wangzul @zimu-yuxi 

老师好！请问这部分的源码在什么位置？ secretpad 这个service的name只能是secretpad吗？ 可以自定义吗？  Thanks

**Comment by gxcuit** [comment]
> 大概确认了，你可以在kuscia容器新建一个service，secretpad的service。正常secretpad的数据同步是借助kuscia的网络进行的，比如alice的secretpad->alice的kuscia->bob的kuscia->bob的secretpad。然后你的secretpad的gateway换成本方的kuscia的IP和gataway端口，就可以对接多个节点，只要双方kuscia的路由正常建立

> bob的kuscia->bob的secretpad

请问，bob的kuscia 是如何找到bob的secretpad的？externalName 只能叫 `secretpad` 吗

**Comment by zimu-yuxi** [comment]
> > 大概确认了，你可以在kuscia容器新建一个service，secretpad的service。正常secretpad的数据同步是借助kuscia的网络进行的，比如alice的secretpad->alice的kuscia->bob的kuscia->bob的secretpad。然后你的secretpad的gateway换成本方的kuscia的IP和gataway端口，就可以对接多个节点，只要双方kuscia的路由正常建立
> 
> > bob的kuscia->bob的secretpad
> 
> 请问，bob的kuscia 是如何找到bob的secretpad的？externalName 只能叫 `secretpad` 吗

源码这里看下org.secretflow.secretpad.persistence.datasync.rest.DataSyncRestTemplate

**Comment by gxcuit** [comment]
> > > 大概确认了，你可以在kuscia容器新建一个service，secretpad的service。正常secretpad的数据同步是借助kuscia的网络进行的，比如alice的secretpad->alice的kuscia->bob的kuscia->bob的secretpad。然后你的secretpad的gateway换成本方的kuscia的IP和gataway端口，就可以对接多个节点，只要双方kuscia的路由正常建立
> > 
> > 
> > > bob的kuscia->bob的secretpad
> > 
> > 
> > 请问，bob的kuscia 是如何找到bob的secretpad的？externalName 只能叫 `secretpad` 吗
> 
> 源码这里看下org.secretflow.secretpad.persistence.datasync.rest.DataSyncRestTemplate

Thanks! 我也找到了
