### ISSUE TITLE
开发secretflow新组件遇到问题

### ISSUE THREAD

**Issue by ShaneGu4Real** [secretflow/secretpad#153]
### Issue Type

Feature

### Have you searched for existing issues?

Yes

### Question Details

```shell
您好，我准备新开发一个secretflow组件，遇到以下疑问，麻烦解答下
1，我是Windows环境，是否可以在wsl2里进行组件的开发？
2，我看开发好后，需要打包新镜像，是否我在可以执行docker命令的wsl2里打包就可以
3，我看组件打包的时候（执行命令 sh build.sh -v test_compare），基础镜像是sf-dev-anolis8，这个需要我们额外下载吗，如果是需要去哪里下载，我找了找本地没找到
```

**Comment by wangzul** [comment]
sh build.sh -v test_compare执行这个命令会自行拉取编译环境(镜像)进行编译打包，并产出镜像不需要自行下载，但是需要你有良好的网络访问。

部分镜像需要从dockerhub上拉取

**Comment by ShaneGu4Real** [comment]
@wangzul您好，我可以在wsl2里进行组件的开发吗？，开发好后，需要打包新镜像，是否我在可以执行docker命令的wsl2里打包就可以

**Comment by wangzul** [comment]
> @wangzul您好，我可以在wsl2里进行组件的开发吗？，开发好后，需要打包新镜像，是否我在可以执行docker命令的wsl2里打包就可以

可以的，不过你要考虑网络问题，如果镜像拉不下来需要你找一下资源，配置自己的代理或者是国内的镜像源。

**Comment by ShaneGu4Real** [comment]
谢谢
