### ISSUE TITLE
中心化部署edge节点相互通信不可用，日志显示res({}),err(response status code [503], detail -> no healthy upstream)

### ISSUE THREAD

**Issue by EtanWatson** [secretflow/secretpad#158]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

No

### OS Platform and Distribution

Linux centos7

### All_in_one Version

v1.9.0

### Module type

secretpad

### Module version

0.10.1b0

### What happend and What you expected to happen.

```shell
两个edge通信不可用
```

### Log output.

```shell
INFO utils/http.go:86 [HTTP] method(POST),uri(kuscia-handshake.xzykkttr.svc),path(/handshake),req({"domain_id":"ylospxaz","type":"RSA","token_config":{"token":"","pubhash":""},"request_time":1729753742634265472}),res({}),err(response status code [503], detail -> no healthy upstream)
```

**Comment by zimu-yuxi** [comment]
1.新增的节点是在同一台机器上吗？
2.可以将通讯地址换成真实的IP和端口尝试下

**Comment by Chrisdehe** [comment]
@EtanWatson 你好，方便咨询一下这个问题如何解决的吗，新增的节点是在同一台机器吗？
