### ISSUE TITLE
特征列和值长度限制

### ISSUE THREAD

**Issue by EightMonth** [secretflow/secretpad#162]
### Issue Type

Running

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

18.04

### All_in_one Version

v0.10.0

### Module type

secretflow

### Module version

v1.12

### What happend and What you expected to happen.

```shell
特征列和值长度被限制，无法运行
```

### Log output.

```shell
label key and value length (129732 bytes) greater than maximum size (4096 bytes), key: kuscia.secretflow.comp_list: invalid argument
```

**Comment by lanyy9527** [comment]
是在什么场景、做了什么操作出现的该问题；

**Comment by EightMonth** [comment]
就是引入了两个数据表，含有5个特征列，进行求交，就发生了这个报错

**Comment by lanyy9527** [comment]
是在pad平台中基于训练流进行求交，还是通过secretflow API来进行求交的；如果是pad层可提供下相关截图及报错信息、和测试数据，若是sf层可提供下代码及数据；

**Comment by lanyy9527** [comment]
可以提供下双方的测试数据；

**Comment by EightMonth** [comment]
[married.csv](https://github.com/user-attachments/files/17812496/married.csv)
[public.csv](https://github.com/user-attachments/files/17812498/public.csv)

**Comment by lanyy9527** [comment]
> [married.csv](https://github.com/user-attachments/files/17812496/married.csv) [public.csv](https://github.com/user-attachments/files/17812498/public.csv)

使用该数据没有复现上面的报错信息；可以检查下在上传数据时schema读取的是否正确；
