### ISSUE TITLE
secretpad如何启用拆分学习NN组件

### ISSUE THREAD

**Issue by beng003** [secretflow/secretpad#168]
### Issue Type

Api Usage

### Have you searched for existing issues?

Yes

### Question Details

```shell
看相关文档描述要使用完整版的secretflow镜像，并且环境变量ENABLE_NN设置为true。想请教一下以下问题：

1.如果想要添加组件修改打包注册secretflow镜像，怎么使用打包完整镜像？
2.环境变量ENABLE_NN设置为true是需要在kuscia-master、kuscia-lite和secretpad容器中都做设置吗？
```

**Comment by zimu-yuxi** [comment]
1.参考[这里](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b1/getting_started/installation)，不使用secretflow-lite就行
2.secretpad不需要

**Comment by beng003** [comment]
> 1.参考[这里](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b1/getting_started/installation)，不使用secretflow-lite就行 2.secretpad不需要

1. 您好，我想知道使用secretpad添加组件脚本 [sh build.sh -v test_compare](https://github.com/secretflow/docs/blob/v1.10.0b1/docs/all-in-one/more_tutorials/new_components.md#%E6%89%93%E5%8C%85%E9%95%9C%E5%83%8F)是打包secretflow镜像来替换原有的secretflow镜像吗？如果是secretflow镜像怎么修改文件打包完整版的secretflow镜像？以及之后怎么在secretpad前端使用拆分学习NN组件（是否需要修改环境变量）？

2. 还是说需要自己构建secretpad安装包，然后参考[文档](https://github.com/secretflow/secretpad/blob/7fd96a031094b6a1965621301bf782efd6645830/docs/development/build_mvp.md#mvp-%E6%9E%84%E5%BB%BA)，修改secretflow镜像为完整镜像？或者不用自己构建secretpad安装包，只需要在secretpad-all-in-one包中修改一键安装脚本，指定使用secretflow镜像为完整镜像？

3. 在安装完整版secretflow镜像的secretpad中使用脚本 [sh build.sh -v test_compare](https://github.com/secretflow/docs/blob/v1.10.0b1/docs/all-in-one/more_tutorials/new_components.md#%E6%89%93%E5%8C%85%E9%95%9C%E5%83%8F)继续添加新的组件需要修改一些地方吗？[比如](脚本 [sh build.sh -v test_compare](https://github.com/secretflow/docs/blob/v1.10.0b1/docs/all-in-one/more_tutorials/new_components.md#%E6%89%93%E5%8C%85%E9%95%9C%E5%83%8F))

**Comment by zimu-yuxi** [comment]
如果自己打包镜像，你需要在[此处](https://github.com/secretflow/secretflow/blob/main/docker/dev/entry.sh)文件，修改python3 setup.py bdist_wheel --lite为python3 setup.py bdist_wheel

**Comment by beng003** [comment]
> 如果自己打包镜像，你需要在[此处](https://github.com/secretflow/secretflow/blob/main/docker/dev/entry.sh)文件，修改python3 setup.py bdist_wheel --lite为python3 setup.py bdist_wheel

你好，我想问一下为什么使用完整版的secretflow镜像在secretpad中依旧没有拆分学习NN组件？还需要调整什么？针对[问题](https://github.com/secretflow/secretpad/issues/168#issuecomment-2497245090)希望做出更详细的解答

**Comment by zimu-yuxi** [comment]
> > 如果自己打包镜像，你需要在[此处](https://github.com/secretflow/secretflow/blob/main/docker/dev/entry.sh)文件，修改python3 setup.py bdist_wheel --lite为python3 setup.py bdist_wheel
> 
> 你好，我想问一下为什么使用完整版的secretflow镜像在secretpad中依旧没有拆分学习NN组件？还需要调整什么？针对[问题](https://github.com/secretflow/secretpad/issues/168#issuecomment-2497245090)希望做出更详细的解答

secretpad的源码中将slnn_train组件隐藏了，
![image](https://github.com/user-attachments/assets/489dec94-5d42-4167-86ca-e45e7892c7c4)
你需要修改配置，在secretpad容器内，路径app/config/application.yaml，修改此处配置，然后重启secretpad容器

**Comment by beng003** [comment]
> > > 如果自己打包镜像，你需要在[此处](https://github.com/secretflow/secretflow/blob/main/docker/dev/entry.sh)文件，修改python3 setup.py bdist_wheel --lite为python3 setup.py bdist_wheel
> > 
> > 
> > 你好，我想问一下为什么使用完整版的secretflow镜像在secretpad中依旧没有拆分学习NN组件？还需要调整什么？针对[问题](https://github.com/secretflow/secretpad/issues/168#issuecomment-2497245090)希望做出更详细的解答
> 
> secretpad的源码中将slnn_train组件隐藏了， ![image](https://private-user-images.githubusercontent.com/72854640/389490782-489dec94-5d42-4167-86ca-e45e7892c7c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzM0OTAsIm5iZiI6MTczMjUzMzE5MCwicGF0aCI6Ii83Mjg1NDY0MC8zODk0OTA3ODItNDg5ZGVjOTQtNWQ0Mi00MTY3LTg2Y2EtZTQ1ZTc4OTJjN2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDExMTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YjgxZWUxMWZlZGU2OGYxYzRlOGYwMWE4MzU3ODYwYWI2NzE5MDNhZjcxYTk5NzBjYjhiNDI3OTcxOWRmYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bOLiLg7IB7rVwAuv6EcB4VYAwDCTsIIyCF4_O3KHEQU) 你需要修改配置，在secretpad容器内，路径app/config/application.yaml，修改此处配置，然后重启secretpad容器

好的，感谢

但是拆分学习NN组件在使用的时候报错了，是该组件目前还不可以使用吗？报错如下：
`2024-11-25 19:30:36 INFO the jobId=cmor, taskId=cmor-qysmpvny-node-35 start ...
2024-11-25 19:30:50 INFO the jobId=cmor, taskId=cmor-qysmpvny-node-35 failed: party alice failed msg: container[secretflow] terminated state reason "Error", message: "  ValueError: Could not find matching concrete function to call loaded from the SavedModel. Got:
          Positional arguments (3 total):
            * <tf.Tensor 'inputs:0' shape=(512, 24) dtype=float32>
            * True
            * None
          Keyword arguments: {}
        
         Expected these arguments to match one of the following 4 option(s):
        
        Option 1:
          Positional arguments (3 total):
            * TensorSpec(shape=(None, 12), dtype=tf.float32, name='input_1')
            * True
            * None
          Keyword arguments: {}
        
        Option 2:
          Positional arguments (3 total):
            * TensorSpec(shape=(None, 12), dtype=tf.float32, name='input_1')
            * False
            * None
          Keyword arguments: {}
        
        Option 3:
          Positional arguments (3 total):
            * TensorSpec(shape=(None, 12), dtype=tf.float32, name='inputs')
            * True
            * None
          Keyword arguments: {}
        
        Option 4:
          Positional arguments (3 total):
            * TensorSpec(shape=(None, 12), dtype=tf.float32, name='inputs')
            * False
            * None
          Keyword arguments: {}
    
    
    Call arguments received by layer 'wrapper_model' (type WrapperModel):
      • x=tf.Tensor(shape=(512, 24), dtype=float32)

2024-11-25 11:30:47.935 ERROR brpc_link.py:150 [alice] -- Receiving exception: <class 'secretflow.distributed.fed.exception.FedRemoteError'>, FedRemoteError occurred at bob caused by object of type 'NoneType' has no len() from bob, seq id 81. Re-raise it.
2024-11-25 11:30:49.667 WARNING object.py:41 [alice] -- get obj interrupted by FedRemoteError occurred at bob caused by object of type 'NoneType' has no len()
2024-11-25 11:30:49.669 WARNING object.py:41 [alice] -- get obj interrupted by FedRemoteError occurred at bob caused by object of type 'NoneType' has no len()
2024-11-25 11:30:49.670 ERROR brpc_link.py:150 [alice] -- Receiving exception: <class 'secretflow.distributed.fed.exception.FedRemoteError'>, FedRemoteError occurred at bob caused by object of type 'NoneType' has no len() from bob, seq id 95. Re-raise it.
2024-11-25 11:30:49.677 WARNING object.py:41 [alice] -- get obj interrupted by FedRemoteError occurred at bob caused by object of type 'NoneType' has no len()
2024-11-25 11:30:49.677 WARNING api.py:309 [alice] -- Encounter RemoteError happend in other parties, error message: object of type 'NoneType' has no len()
2024-11-25 11:30:49.677 ERROR entry.py:176 [alice] -- comp eval failed, error <FedRemoteError occurred at bob caused by object of type 'NoneType' has no len()>
Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/core/entry.py\", line 156, in comp_eval
    comp.evaluate(ctx)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/ml/nn/sl/sl_train.py\", line 224, in evaluate
    slmodel, history, model_configs = trainer.fit(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/component/ml/nn/sl/training/trainer.py\", line 146, in fit
    history = slmodel.fit(
  File \"/usr/local/lib/python3.10/site-packages/secretflow/ml/nn/sl/sl_model.py\", line 661, in fit
    wait(res)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/driver.py\", line 212, in wait
    reveal([o.device(lambda o: None)(o) for o in objs])
  File \"/usr/local/lib/python3.10/site-packages/secretflow/device/driver.py\", line 161, in reveal
    all_object = sfd.get(all_object_refs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/primitive.py\", line 160, in get
    return sf_fed.get(object_refs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/api.py\", line 307, in get
    flattened_args[i] = copy.deepcopy(flattened_args[i].get_object())
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py\", line 117, in get_object
    self._object = self._object.get()
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py\", line 42, in get
    raise exception
  File \"/usr/local/lib/python3.10/concurrent/futures/thread.py\", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/global_context.py\", line 203, in _recv
    data = self._proxy.recv(src_party, seq_id)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/proxy/brpc_link/brpc_link.py\", line 179, in recv
    return _pop_data()
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/proxy/brpc_link/brpc_link.py\", line 157, in _pop_data
    raise data
secretflow.distributed.fed.exception.FedRemoteError: FedRemoteError occurred at bob caused by object of type 'NoneType' has no len()
2024-11-25 11:30:49.684 INFO driver.py:548 [alice] -- shutdown is called, barrier_on_shutdown False, on_error True
2024-11-25 11:30:49.684 INFO api.py:214 [alice] -- Shutdowning intendedly, wait_for_sending False
2024-11-25 11:30:49.684 INFO global_context.py:214 [alice] -- Try stop context, wait_for_sending False, on_error True
2024-11-25 11:30:49.684 INFO global_context.py:218 [alice] -- task_executor stoped
2024-11-25 11:30:49.685 INFO global_context.py:220 [alice] -- recv_executor stoped
2024-11-25 11:30:49.685 INFO global_context.py:224 [alice] -- send_executor stoped
2024-11-25 11:30:49.685 INFO global_context.py:237 [alice] -- Context stoped
2024-11-25 11:30:49.854 ERROR global_context.py:163 [alice] -- Local runtime error
Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/global_context.py\", line 158, in _send
    obj = fed_obj.get_object()
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py\", line 117, in get_object
    self._object = self._object.get()
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py\", line 39, in get
    exception = get_global_context().get_last_exception()
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/global_context.py\", line 263, in get_global_context
    raise RuntimeError(\"sf_fed is stoped or not init\")
RuntimeError: sf_fed is stoped or not init
2024-11-25 11:30:49.857 ERROR global_context.py:183 [alice] -- FedLocalError on seq id 91
Traceback (most recent call last):
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/global_context.py\", line 177, in _send_check
    send_future.result()
  File \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 458, in result
    return self.__get_result()
  File \"/usr/local/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result
    raise self._exception
  File \"/usr/local/lib/python3.10/concurrent/futures/thread.py\", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/global_context.py\", line 170, in _send
    raise local_err
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/global_context.py\", line 158, in _send
    obj = fed_obj.get_object()
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py\", line 117, in get_object
    self._object = self._object.get()
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/object.py\", line 39, in get
    exception = get_global_context().get_last_exception()
  File \"/usr/local/lib/python3.10/site-packages/secretflow/distributed/fed/global_context.py\", line 263, in get_global_context
    raise RuntimeError(\"sf_fed is stoped or not init\")
secretflow.distributed.fed.exception.FedLocalError: sf_fed is stoped or not init
2024-11-25 11:30:49.857 ERROR brpc_link.py:150 [alice] -- Receiving exception: <class 'secretflow.distributed.fed.exception.FedRemoteError'>, FedRemoteError occurred at bob caused by object of type 'NoneType' has no len() from bob, seq id 109. Re-raise it.
2024-11-25 11:30:49.864 INFO api.py:222 [alice] -- Shutdowned
2024-11-25 11:30:49.864 CRITICAL api.py:225 [alice] -- Exit now due to the previous error.
"`

训练数据为内置alice和bob

**Comment by zimu-yuxi** [comment]
方便将训练组件的配置发一下吗？感谢！

**Comment by beng003** [comment]
> 方便将训练组件的配置发一下吗？感谢！


<div style="display: flex; justify-content: space-around; align-items: center;">
    <img src="https://github.com/user-attachments/assets/205cfeae-57a8-48de-b5e3-5cdc67e4b6bb" alt="配置1" width="35%">
    <img src="https://github.com/user-attachments/assets/32232942-85c3-4363-9423-cd8bda665a63" alt="配置1" width="40%">
    <img src="https://github.com/user-attachments/assets/fb1d3556-c151-44b9-9832-0a989b9d659d" alt="配置1" width="30%">
    <img src="https://github.com/user-attachments/assets/d1ddf300-1790-43ac-bcc0-62eee8400cfe" alt="配置2" width="30%">
    <img src="https://github.com/user-attachments/assets/1be29e1d-2bc9-45c4-ad8f-306d59b7018d" alt="配置3" width="30%">
</div>

**Comment by zimu-yuxi** [comment]
看下模型这里配置的是否正确，参考[此处](https://github.com/secretflow/secretflow/blob/54413f9d424435f127a5d161e3fc204cea85594b/secretflow/component/ml/nn/sl/base.py#L155)

**Comment by beng003** [comment]
> 看下模型这里配置的是否正确，参考[此处](https://github.com/secretflow/secretflow/blob/54413f9d424435f127a5d161e3fc204cea85594b/secretflow/component/ml/nn/sl/base.py#L155)

模型参数配置使用的都是默认值，需要修改吗？

其实确实有个问题想问，模型函数代码是以字符串的形式提供的，代码换行等是如何处理的？
