### ISSUE TITLE
SecretPad逻辑回归预测结果异常

### ISSUE THREAD

**Issue by Inclay97** [secretflow/secretpad#170]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

Linux version 4.19.90-52.40.v2207.ky10.x86_64 (KYLINSOFT@f4c0be98561f) (gcc version 7.3.0 (GCC)) #3 SMP Wed Jul 24 15:07:09 CST 2024

### All_in_one Version

SecretPad All In One v1.9.0

### Module type

secretflow

### Module version

SecretPad All In One v1.9.0

### What happend and What you expected to happen.

```shell
能够正常运行得到结果，但在使用逻辑回归模型训练并预测二分类问题时（0，1）得到的预测结果却为0.5
```

### Log output.

```shell
能够正常运行得到结果，但在使用逻辑回归模型训练并预测二分类问题时（0，1）得到的预测结果却为0.5
```

**Comment by Inclay97** [comment]
![image](https://github.com/user-attachments/assets/730667f8-f217-4fa0-aaf2-b5b0d26ccca9)
训练流

**Comment by Inclay97** [comment]
分箱操作内容：
![image](https://github.com/user-attachments/assets/16192d1f-9af2-4d27-bf04-8c821379c807)

逻辑回归训练参数
![image](https://github.com/user-attachments/assets/5674c560-8729-4778-b046-fe178f012ba2)

**Comment by Inclay97** [comment]
数据集
[heart.csv](https://github.com/user-attachments/files/17900994/heart.csv)

**Comment by Inclay97** [comment]
预测结果
![image](https://github.com/user-attachments/assets/79d60ffd-eed5-4a02-bdf1-3e178b5c4c8b)

**Comment by zimu-yuxi** [comment]
尝试将逻辑回归的训练批数据量改为10后重新进行模型训练，然后发布模型，再次预测一下

**Comment by Inclay97** [comment]
![image](https://github.com/user-attachments/assets/30b0fd70-54cf-490a-b9e1-b1f0450db7db)
改了之后，结果如上，为何预测结果不会是0或1，而是一个概率值

**Comment by zimu-yuxi** [comment]
模型的预测值可以简单表示为特征值和系数的点乘再加上偏置，可以看下[这里](https://www.secretflow.org.cn/zh-CN/docs/serving/0.7.0b0/topics/algorithm/intro)。

**Comment by Inclay97** [comment]
那以上预测结果是没有问题的，且我可以理解成 预测值大于0.5的为正类，小于0.5的为负类吗？

**Comment by zimu-yuxi** [comment]
是的
