### ISSUE TITLE
Kuscia怎么删除没有用的注册自定义算法镜像？

### ISSUE THREAD

**Issue by beng003** [secretflow/secretpad#171]
### Issue Type

Api Usage

### Have you searched for existing issues?

Yes

### Question Details

```shell
Kuscia怎么删除没有用的注册自定义算法镜像？
```

**Comment by wangzul** [comment]
脚本改动是能满足更新自定义镜像的作用，原有的逻辑为检测kuscia是否已经注册相同名称镜像，你这边的改动是直接放行不做这个检测判断了。
