### ISSUE TITLE
secretpad上传其他格式文件(如json)需要修改什么地方？

### ISSUE THREAD

**Issue by beng003** [secretflow/secretpad#172]
### Issue Type

Api Usage

### Have you searched for existing issues?

No

### Question Details

```shell
你好，我们想咨询一下secretpad想要上传其他格式文件(如json)需要修改什么地方？
场景：某一方上传自定义模型等，再利用联合数据和自定义组件进行训练
```

**Comment by beng003** [comment]
![微信截图_20241127153508](https://github.com/user-attachments/assets/7456b78f-992f-4ecc-8733-ee0e65ccb764)

**Comment by lanyy9527** [comment]
不支持在secretpad直接上传自定义模型

**Comment by lanyy9527** [comment]
需要在secretflow中加载模型，参考[这里](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.10.0b1/tutorial/Pytorch-finetune-alexnet)
