### ISSUE TITLE
build.sh: line 95:/usr/bin/docker: Argument list too long

### ISSUE THREAD

**Issue by beng003** [secretflow/secretpad#174]
### Issue Type

Api Usage

### Have you searched for existing issues?

Yes

### Link to Relevant Documentation

https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.10.0b1/more_tutorials/new_components#id14

### Question Details

```shell
利用脚本添加组件，组件过多会报错build.sh: line 95:/usr/bin/docker: Argument list too long
```

**Comment by beng003** [comment]
[教程](https://github.com/secretflow/docs/blob/57c41fa8a7caa46fa4dd4bd94d6dcda71debd06e/docs/all-in-one/more_tutorials/new_components.md#%E6%89%93%E5%8C%85%E9%95%9C%E5%83%8F)中使用的打包脚本打包镜像的时候，添加的组件过多会报错（新添加3个组件）。删除一些自带的组件可以解决问题，有什么办法不删除已有的组件继续添加新的组件吗？

**Comment by BrainWH** [comment]
编译docker的时候，数据的参数过长导致的。目前需要将生成的comp_list.json和translation.json文件中的内容，手动写入到Dockerfile中，同时注意对引号、回车符、反斜杠进行转译处理；这个问题在后续的版本中会进行修复。

**Comment by beng003** [comment]
> 编译docker的时候，数据的参数过长导致的。目前需要将生成的comp_list.json和translation.json文件中的内容，手动写入到Dockerfile中，同时注意对引号、回车符、反斜杠进行转译处理；这个问题在后续的版本中会进行修复。

好的
