### ISSUE TITLE
MYSQL 数据暂不支持使用模型训练、特征处理类型组件相关问题询问

### ISSUE THREAD

**Issue by beng003** [secretflow/secretpad#176]
### Issue Type

Api Usage

### Have you searched for existing issues?

Yes

### Question Details

```shell
MYSQL数据源不支持模型训练，但我在后续的模型训练中可以进行模型训练，想问页面上为什么之前说不行？
```

**Comment by beng003** [comment]
<img src="https://github.com/user-attachments/assets/b0129b8c-a60f-4a44-99e3-881d0f1c7b3c" width="400"/>
<img src="https://github.com/user-attachments/assets/b36a0366-caa6-4779-ae2a-8a89cdf33a59" height="400"/>

**Comment by lanyy9527** [comment]
目前mysql数据表可以跑隐私求交这些组件，但是不能跑训练、模型预测这些组件；
右上角全局配置中有选项，需要选择mysql数据源，否则默认是local本地数据源，最后产出的结果仍在本地，所以可以执行成功；

**Comment by beng003** [comment]
> 目前mysql数据表可以跑隐私求交这些组件，但是不能跑训练、模型预测这些组件； 右上角全局配置中有选项，需要选择mysql数据源，否则默认是local本地数据源，最后产出的结果仍在本地，所以可以执行成功；

好的，谢谢
