### ISSUE TITLE
怎么在组件中实现类似样本表的作用

### ISSUE THREAD

**Issue by beng003** [secretflow/secretpad#177]
### Issue Type

Api Usage

### Have you searched for existing issues?

Yes

### Question Details

```shell
我们想实现一个组件，要求输入需要保存到数据库中的数据，然后可以通过类似样本表选择数据的形式获得msyql数据库数据表链接信息来保存到指定的表

想请教一下需要怎么获得数据库数据表链接信息并传给组件选择？
```

**Comment by zimu-yuxi** [comment]
在secretpad侧新增组件，参考[此处代码](https://github.com/secretflow/secretpad/blob/main/secretpad-service/src/main/java/org/secretflow/secretpad/service/graph/adapter/NodeDefAdapter.java)

注：已线下解决
