### ISSUE TITLE
secretpad部署问题咨询

### ISSUE THREAD

**Issue by walkovernamtso** [secretflow/secretpad#179]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
中心化部署模式下，我理解是在中心部署secretpad center平台，在边缘部署secretpad edge平台。 
这两者是一个包对吗，如何区分中心部署和边缘部署？
查看部署脚本，secretpad.sh里面也没有看出如何区分的中心部署和边缘部署
请教各位专家！
```

**Comment by zimu-yuxi** [comment]
是一个包，通过入参在install.sh部署脚本中区分的

**Comment by walkovernamtso** [comment]
多谢指导！我说的secretpad指的是secretpad镜像，不是那个allinone大包，allinone大包的安装是通过install.sh区分的，看到了。现在不太清楚的是，中心部署secretpad center平台，在边缘部署secretpad edge平台。这是如何区分的？

**Comment by zimu-yuxi** [comment]
首先center和edge是一个secretpad镜像，不管是中心化部署（center，edge）还是P2P（edge）部署用的都是一套代码

注：alice，bob，tee是我们内置的节点，只有一个master的secretpad容器，你可以尝试部署install.sh lite部署（edge），也会启动一个secretpad容器

**Comment by zimu-yuxi** [comment]
‘deploy_kuscia---这里面能看出中心和边缘部署的不一样’，在kuscia中，中心化部署对于center，其实就是master（控制平面节点），edge，就是lite（任务计算节点），P2P部署对于edge，就是autonomy（控制平面+任务计算）。

如上所讲，在prepare_environment（具体逻辑可以看下[这里](https://github.com/secretflow/secretpad/blob/fdba9c3c79b1cdc0c95421368949703bd56f2b6b/scripts/deploy/common/utils.sh#L247)）时，根据master。lite，autonomy来给SPRING_PROFILES_ACTIVE环境变量赋值，在启动secretpad容器时会带上此变量的，参考[这里](https://github.com/secretflow/secretpad/blob/fdba9c3c79b1cdc0c95421368949703bd56f2b6b/scripts/deploy/secretpad.sh#L342)

**Comment by walkovernamtso** [comment]
找到了，谢谢
