### ISSUE TITLE
Secretpad联邦学习 woe转换报错

### ISSUE THREAD

**Issue by Jymjiaym** [secretflow/secretpad#18]
![IMG_1013](https://github.com/secretflow/secretpad/assets/93430715/27f0a4fa-6efa-4fbc-91fa-a8fb772843e3)
![Uploading IMG_1010.jp
![IMG_1008](https://github.com/secretflow/secretpad/assets/93430715/0a5e5426-d3bf-4b98-909d-6794fe2dfb58)
eg…]()

**Comment by xiushuiguande** [comment]
@Jymjiaym hi，把woe配置发一下吧

**Comment by Jymjiaym** [comment]
> @Jymjiaym hi，把woe配置发一下吧

woe转换没配置
![Uploading image.jpg…]()

**Comment by xiushuiguande** [comment]
@Jymjiaym hi，看不到你上传的图片，辛苦修改下？

**Comment by Jymjiaym** [comment]
> @Jymjiaym hi，看不到你上传的图片，辛苦修改下？

平台woe转换不用配置
![Uploading IMG_1014.jpeg…]()

**Comment by Jymjiaym** [comment]
我整体补充一下现象图片。
![现象1](https://github.com/secretflow/secretpad/assets/93430715/51ed9187-c3ff-43e4-a155-baad4e38343f)
![现象2](https://github.com/secretflow/secretpad/assets/93430715/c975e667-80bb-4b02-8afa-28bee5138c9e)
![现象3](https://github.com/secretflow/secretpad/assets/93430715/e2e3a999-c0e7-4169-a06e-f5d6f466053c)
![现象4](https://github.com/secretflow/secretpad/assets/93430715/4bc62f36-9f3b-4d7e-b41a-df4544f6dc31)

**Comment by da-niao-dan** [comment]
你好， 连线数量不对，需要两个实际连上了一个， woe 转换的所有输入桩需要都连上正确输入

**Comment by xujiening** [comment]
@Jymjiaym 你好，woe转换需要两个输入，一个是垂直分区的数据集，一个是转换规则，只有一条连线是跑不成功的

**Comment by Jymjiaym** [comment]
明白了 谢谢老师解答
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月11日 12:00 |
| 收件人 | secretflow/secretpad ***@***.***> |
| 抄送人 | Jymjiaym ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [secretflow/secretpad] Secretpad联邦学习 woe转换报错 (Issue #18) |

@Jymjiaym 你好，我们的金融风控模板有完整的示例，woe转换经过数据分割跟woe分箱之后再进行woe转换
