### ISSUE TITLE
中心模式合作节点通讯状态为不可用

### ISSUE THREAD

**Issue by hdkoutann** [secretflow/secretpad#180]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

Alibaba Cloud Linux release 3

### All_in_one Version

0.11.0b0

### Module type

secretpad

### Module version

0.11.0b0

### What happend and What you expected to happen.

```shell
创建合作的两个节点 ： 
1. 中心节点内置节点 ： alice
2. 另外一台服务器注册的节点： remote
两个节点创建合作项目： alice节点显示通讯状态可用； remote节点显示不可用；是什么原因，如何排查

通讯协议 ：tls
```

### Log output.

```shell
无
```

**Comment by zimu-yuxi** [comment]
确认下‘通讯协议 ：tls’，是指alice和remote都是tls吗？
在remote添加合作节点时，
1 确认下alcie的通讯地址是否为宿主机的IP
2 确认下alcie的通讯协议是否正确，在/home/kuscia/etc/conf/kuscia.yaml看下protocol，如果是notls那么应使用http，tls/mtls使用https

**Comment by hdkoutann** [comment]
已确认： alice 通讯地址 - protocol: tls；   通讯地址配置的是：
https://10.53.89.228:28080； 这个端口应该用28080 还是1080？改成1080也链接不上
alice的端口映射如下：
22aca0cf538e   secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:0.12.0b0      "tini -- bin/kuscia …"   6 days ago   Up 6 days   0.0.0.0:23081->80/tcp, 0.0.0.0:28080->1080/tcp, 0.0.0.0:28082->8082/tcp, 0.0.0.0:28083->8083/tcp, 0.0.0.0:23084->9091/tcp   root-kuscia-lite-alice
