### ISSUE TITLE
P2P部署，训练流任务执行完成后，两个参与方都无法下载数据

### ISSUE THREAD

**Issue by WandQ** [secretflow/secretpad#182]
### Issue Type

Feature

### Have you searched for existing issues?

Yes

### Question Details

```shell
运行的联合圈人模板，隐私求交结果数据和全表统计数据都显示“非数据参与方，无计算结果”
```

**Comment by WandQ** [comment]
![image](https://github.com/user-attachments/assets/be9b33ce-8293-47e9-8a0f-38afa55e55f7)


![image](https://github.com/user-attachments/assets/fbc3c32d-6538-479f-89c8-d50b73783f14)

**Comment by BrainWH** [comment]
可以提供一下all in one的版本信息

**Comment by WandQ** [comment]
@BrainWH 

secretpadImage版本：0.11.0b0
secretflowServingImage版本：0.7.0b0
kusciaImage版本：0.12.0b0
secretflowImage版本：1.10.0b1
dataProxyImage版本：0.1.0b0

最近在官网下的最新版

**Comment by BrainWH** [comment]
可以描述一下具体的操作步骤吗？

**Comment by WandQ** [comment]
部署阶段：
sudo bash install.sh autonomy -n alice -s 8088 -g 18083 -k 18082 -p 18080 -q 13081 -x 18084 -P mtls
sudo bash install.sh autonomy -n bob -s 8089 -g 18183 -k 18182 -p 18180 -q 13181 -x 18184 -P mtls

建立节点链接：
![image](https://github.com/user-attachments/assets/b01fb385-f694-4017-b637-51e39ddedfb6)
![image](https://github.com/user-attachments/assets/2d2623ab-6c02-4214-9d24-d2a53a1f86ec)
通信状态均可用

添加数据：
通过本地数据源上传CSV


新建项目：
![image](https://github.com/user-attachments/assets/00dde448-9262-4220-aa12-e0dbad46169a)


数据授权：
![image](https://github.com/user-attachments/assets/3c64876c-0c01-4074-8445-63f6b05fedf2)
![image](https://github.com/user-attachments/assets/ce8ef8bd-92f0-4a99-9fd3-e560b587af96)


新建数据流：
![image](https://github.com/user-attachments/assets/068c9330-65cc-4420-b5fa-cbf2959adf67)
![image](https://github.com/user-attachments/assets/48fa8ac2-5ced-472b-97fc-d53fdc1399a3)

全部执行，
![image](https://github.com/user-attachments/assets/c60d2205-9d43-4faf-9f6d-a4771796fb9c)

**Comment by BrainWH** [comment]
看到最后一张图的训练流的名称是1，倒数第二张图的训练流的名称是联合圈人，看起来不是同一个训练流。

**Comment by WandQ** [comment]
> 看到最后一张图的训练流的名称是1，倒数第二张图的训练流的名称是联合圈人，看起来不是同一个训练流。

名字是为了截图导致的，现在有点奇怪的是我按照这个流程做都是这样的，
![image](https://github.com/user-attachments/assets/faf8d105-c828-43f0-9ca1-4c1ef95b3f7a)

**Comment by BrainWH** [comment]
先把id1, id2 的保护开关关掉，再重新跑一下训练流，看一下结果

**Comment by WandQ** [comment]
![image](https://github.com/user-attachments/assets/3f9c41c0-2594-4c8e-a2ee-dc4b2c8c2de2)
![image](https://github.com/user-attachments/assets/c2295ff7-ac12-455b-8076-9cbd55a94d34)

结果：
![image](https://github.com/user-attachments/assets/b31dc0d0-913c-4ecc-985e-7048346e2fd9)
然后执行，还是一样的，不能查看 @BrainWH

**Comment by WandQ** [comment]
有一个现象，我换了一台虚拟机，按照相同的步骤复现不了这个问题，能够顺利下载，是不是我重装的时候有什么东西需要清理呀？ @BrainWH

**Comment by BrainWH** [comment]
在之前的虚拟机里，id1, id2 的保护开关打开的时候，在容器内部找到 /home/kuscia/var/stdout/pods/alice_xxxx/secretflow/0.log，把这个0.log贴一下

**Comment by WandQ** [comment]
> 在之前的虚拟机里，id1, id2 的保护开关打开的时候，在容器内部找到 /home/kuscia/var/stdout/pods/alice_xxxx/secretflow/0.log，把这个0.log贴一下

bash-5.2# pwd
/home/kuscia
bash-5.2# cd var/stdout/pods/
bash-5.2# ls
alice_dataproxy-alice-b6bf8ffbb-v2p9f_5bf441f4-34a9-4a52-a3d8-80db46c72351  alice_fdjv-sisacuxb-node-4-0_b239fd85-2b77-4451-9887-3e77389d198c
alice_fdjv-sisacuxb-node-3-0_1034b369-ffed-4082-a018-aef877c4a940
bash-5.2# cd alice_fdjv-sisacuxb-node-3-0_1034b369-ffed-4082-a018-aef877c4a940
bash-5.2# ls
secretflow
bash-5.2# cat secretflow/0.log
bash-5.2#
貌似是个空的日志
