### ISSUE TITLE
[权限管理] secrtePad权限设计的思路是什么

### ISSUE THREAD

**Issue by john8628** [secretflow/secretpad#22]
目前搭建了最新的MVP版本，分别有主账号，新增节点的账号；
问题是： 如何实现实现项目的权限管理；让合作的算法工程师，只看到自己节点的信息和项目，而看不到其他非合作节点的？同时也能基于合作节点数据和自己数据建模

**Comment by leochenJav** [comment]
首先,平台搭建完成之后,edge侧有自己的登录平台,自己的登录平台登录进去之后,可以设置自己在中心平台的密码,账号是节点id
然后登录到中心平台,登录之后,就能满足你第一个诉求,只能看到自己的节点信息和项目
第二个诉求是同时也能基于合作节点数据和自己数据建模,这样要通过跟某个合作节点达成路由的创建,创建完成路由之后,还要进行数据表的授权,在这样的前提下 双方就能基于合作节点的数据和自己的数据建模

**Comment by john8628** [comment]
目前节点只能看到数据管理、合作节点、结果管理，并不能看到项目和配置模型；目前是基于中心化集群的搭建https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/deployment/deploy_master_lite_cn

**Comment by leochenJav** [comment]
基于中心化模式,只能在中心侧看到项目,看之前回复,登录中心侧

**Comment by john8628** [comment]
> 能在中心侧看到项目,看之前回复,登录

那在中心册，可以做区分不同账号角色吗，超级用户，节点项目用户？

**Comment by guixq** [comment]
> 首先,平台搭建完成之后,edge侧有自己的登录平台,自己的登录平台登录进去之后,可以设置自己在中心平台的密码,账号是节点id 然后登录到中心平台,登录之后,就能满足你第一个诉求,只能看到自己的节点信息和项目 第二个诉求是同时也能基于合作节点数据和自己数据建模,这样要通过跟某个合作节点达成路由的创建,创建完成路由之后,还要进行数据表的授权,在这样的前提下 双方就能基于合作节点的数据和自己的数据建模

关于第二个诉求，请问目前开源的scretepad是不是还没有实现相关功能，暂时只能通过kuscia api调用？（我用节点账号登录中心侧并没有找到跟其他节点创建路由的按钮）

**Comment by guixq** [comment]
> 基于中心化模式,只能在中心侧看到项目,看之前回复,登录中心侧
请问application-edge.yaml和application.yaml是secretpad分别部署在lite节点和master节点的机器上时对应的配置文件吗？

**Comment by guixq** [comment]
> 基于中心化模式,只能在中心侧看到项目,看之前回复,登录中心侧

请问application-edge.yaml和application.yaml是secretpad分别部署在lite节点和master节点的机器上时对应的配置文件吗？

**Comment by haha-zwx-ooo** [comment]
> > 基于中心化模式,只能在中心侧看到项目,看之前回复,登录中心侧
> 
> 请问application-edge.yaml和application.yaml是secretpad分别部署在lite节点和master节点的机器上时对应的配置文件吗？

是的
