### ISSUE TITLE
secretpad的最新MVP版本安装问题

### ISSUE THREAD

**Issue by john8628** [secretflow/secretpad#26]
1:install.sh文件中使用最新的版本的kuscia,secret-flow,增加脚本
KUSCIA_IMAGE="secretflow/kuscia:0.5.0b0"
SECRETFLOW_IMAGE="secretflow/secretflow-anolis8:1.3.0b0"

2:执行
sh install.sh p2p -n test -s 8099 -g 8092 -k 8091 -p 8090 -c /root/p2p/test

3:问题：
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/p2p/test" to rootfs at "/home/kuscia/etc/conf/kuscia.yaml": mount /root/p2p/trans-plam:/home/kuscia/etc/conf/kuscia.yaml (via /proc/self/fd/7), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the

**Comment by bulletjet786** [comment]
secretpad目前尚未适配最新的Kuscia，这边建议先仍然使用老版本的kuscia，我们会在后续更新secretpad以适配最新版Kuscia。

**Comment by john8628** [comment]
那我们现在没办法使用较新版本的功能？主要是解决支持千万级的数据预测，隐语较新的sf版本 v1.3.0.dev231219，

**Comment by 6fj** [comment]
可以不更新kuscia吗，只更新sf试一下呢

**Comment by changhr2013** [comment]
这个问题是 secrepad install 脚本内部传参的问题，修改 `install.sh` 脚本中的 `start_kuscia` 方法，将

```shell
cmd_opt="${cmd_opt} -c ${domain_certs_dir}"
```

修改为：

```shell
cmd_opt="${cmd_opt} -s ${domain_certs_dir}"
```

即可。

因为在 `kuscia` 的 `deploy.sh` 脚本中，`-s` 才指代的是证书的路径，`-c` 指代的是 kuscia 的配置文件：

> [deploy.sh](https://github.com/secretflow/kuscia/blob/2075e68bb73523285c84eb0bcb1ea9f0084ee141/scripts/deploy/deploy.sh#L529C1-L529C1)

```shell
...
  case "$option" in
  c)
    KUSCIA_CONFIG_FILE=$(get_absolute_path $OPTARG)
    ;;
  s)
    DOMAIN_CERTS_DIR=$OPTARG
    ;;
...
```

**Comment by john8628** [comment]
> 可以不更新kuscia吗，只更新sf试一下呢

我使用最新的版本的sf，不更新kuscia，会报错
invalid argument "cp -R /app/scripts/start_p2p.sh /tmp/secretpad/" for "-c, --cpu-shares" flag: strconv.ParseInt: parsing "cp -R /app/scripts/start_p2p.sh /tmp/secretpad/": invalid syntax

**Comment by 6fj** [comment]
sf和kuscia应该是解耦的啊， @UniqueMarvin 能看一下吗？感谢

**Comment by john8628** [comment]
> sf和kuscia应该是解耦的啊， @UniqueMarvin 能看一下吗？感谢

@6fj 
部署成功，感谢支持，问题原因：images中 替换了secretpad镜像，但是install.sh未指定secretpad的版本；会出现该问题，

**Comment by 6fj** [comment]
所以现在已经解决问题了是吧

**Comment by john8628** [comment]
> 所以现在已经解决问题了是吧

@6fj 是的，采用的不更新kuscia吗，最新的sf，最新的打包的本地的secretepad;
@changhr2013 你提醒的这种方式，后面尝试一下，这样就能使用最新的kuscia
