### ISSUE TITLE
在使用P-VALUE组件时报错

### ISSUE THREAD

**Issue by RocDDD** [secretflow/secretpad#30]
<img width="779" alt="secretflow_bug1" src="https://github.com/secretflow/secretpad/assets/97602802/dd4571dc-3e09-4d0f-be01-a47ce949440a">

<img width="695" alt="secretflow_bug2" src="https://github.com/secretflow/secretpad/assets/97602802/ff9271a6-6219-4b5b-952b-310220e3c778">
你好，我在用secretpad进行逻辑回归训练时，在P_VALUE 组件运行时报错，特征维度显示是6，但我上游联合表数据是5个特征+1个标签列（subscribe），想问一下为什么会报这个问题。

**Comment by xujiening** [comment]
> <img alt="secretflow_bug1" width="779" src="https://private-user-images.githubusercontent.com/97602802/301425651-dd4571dc-3e09-4d0f-be01-a47ce949440a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDU3ODAsIm5iZiI6MTcwOTU0NTQ4MCwicGF0aCI6Ii85NzYwMjgwMi8zMDE0MjU2NTEtZGQ0NTcxZGMtM2UwOS00ZDBmLWJlMDEtYTQ3Y2U5NDk0NDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhOTRlZTY0M2MwNTc5NjE3OThlNWM5Njc2NzU0M2I5NjBmZjk2YTI5NjhiZTQzZjZhMmJmZGU4YjFhZjc5NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BoWNZVbgloN3DAAykKMuPMuBfYESTZNAcLOXNh-KoYw"> <img alt="secretflow_bug2" width="695" src="https://private-user-images.githubusercontent.com/97602802/301427254-ff9271a6-6219-4b5b-952b-310220e3c778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDU3ODAsIm5iZiI6MTcwOTU0NTQ4MCwicGF0aCI6Ii85NzYwMjgwMi8zMDE0MjcyNTQtZmY5MjcxYTYtNjIxOS00YjViLTk1MmItMzEwMjIwZTNjNzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5NDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZTczNjVjNGMxMjEzNGQzMzgyZGRlOWI2OGUwYTZlYjlmYzAyYTExODEzNzJmMjlkNjE2MmQ5ZTZhYTIxOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Za2z4Rjqbe8_eWFur08_oM5A6bpB9lhCq9B9uVqUrI"> 你好，我在用secretpad进行逻辑回归训练时，在P_VALUE 组件运行时报错，特征维度显示是6，但我上游联合表数据是5个特征+1个标签列（subscribe），想问一下为什么会报这个问题。

你好，你能提供一下你使用的secretpad的版本号的信息吗？按正常了连线的话不应该报错，所以我们要根据版本排查一下

**Comment by RocDDD** [comment]
SF_IMAGE_TAG="1.3.0.dev20231120"

**Comment by xujiening** [comment]
> SF_IMAGE_TAG="1.3.0.dev20231120"

你好，这个版本的sf确实会有这个问题，在1.4.0.dev24011601版本中我们修复了这个问题，您可以使用新版本的sf解决这个问题

**Comment by xujiening** [comment]
> SF_IMAGE_TAG="1.3.0.dev20231120"

你好，这个版本的sf确实会有这个问题，在1.4.0.dev24011601版本中我们修复了这个问题，您可以使用新版本的sf解决这个问题

**Comment by RocDDD** [comment]
好的，感谢你的回复
