### ISSUE TITLE
p2p模式，A，B两个节点，广域网，A->B状态不可用，B-A节点状态可用

### ISSUE THREAD

**Issue by john8628** [secretflow/secretpad#36]
背景：
 A 节点：web secretePad 端口8099；广域网域名www.xxxa.com ,端口80；nginx 转发到8099，kusia gateway 端口8090:配置通讯地址：www.xxxa.com:8090
B 节点 web secretePad 端口8099；广域网域名www.xxxb.com ,端口80；nginx 转发到8099， kusia gateway 端口8090: 配置通讯地址www.xxxb.com:8090

两边web服务可用；但是A->B的通讯状态不可用，telnet www.xxxb.com 8090 是正常的；可能的原因是什么啊？

**Comment by zimu-yuxi** [comment]
直接使用出口ip，把域名换掉试一下

**Comment by zimu-yuxi** [comment]
1.页面添加合作节点修改通信地址后，节点认证码会重新生成，需要重新配置
2.进入kuscia容器看下kuscia日志/home/kuscia/var/logs/kuscai.log，贴一下报错信息

**Comment by john8628** [comment]
感谢回复：
1:发现节点B没有external.log，发现B节点的访问有问题；参考https://www.secretflow.org.cn/zh-CN/docs/kuscia/main/deployment/networkrequirements 文档，目前，问题已经解决
