### ISSUE TITLE
com.secretflow.spec.v1.ComponentDef package can't load

### ISSUE THREAD

**Issue by tututt** [secretflow/secretpad#45]
**Describe the bug**
com.secretflow.spec.v1.ComponentDef package can't load

**Expected behavior**
no

**Actually behavior**
no

**How to Reproduce**

**Additional context**
maven repository also can't find this pacakge

**Comment by tututt** [comment]
应该是需要编译，但是编译报错：[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project secretpad-common: Fatal error compiling: 无效的标记: --release -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project secretpad-common: Fatal error compiling

**Comment by tututt** [comment]
> 应该是需要编译，但是编译报错：[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project secretpad-common: Fatal error compiling: 无效的标记: --release -> [Help 1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project secretpad-common: Fatal error compiling
 # java -version
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Homebrew (build 17.0.10+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.10+0, mixed mode, sharing)

**Comment by tututt** [comment]
> > 应该是需要编译，但是编译报错：[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project secretpad-common: Fatal error compiling: 无效的标记: --release -> [Help 1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project secretpad-common: Fatal error compiling
> 
> # java -version
> openjdk version "17.0.10" 2024-01-16 OpenJDK Runtime Environment Homebrew (build 17.0.10+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.10+0, mixed mode, sharing)

mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /usr/local/Cellar/maven/3.9.6/libexec
Java version: 1.8.0_261, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by wenkesong-li** [comment]
1. 安装编译环境：

- JDK17  设置环境变量
- Maven 设置环境变量

2.刷新Maven 依赖

3.install
mvn clean install -Dmaven.test.skip=true

然后再尝试一下

**Comment by tututt** [comment]
> 1. 安装编译环境：
> 
> * JDK17  设置环境变量
> * Maven 设置环境变量
> 
> 2.刷新Maven 依赖
> 
> 3.install mvn clean install -Dmaven.test.skip=true
> 
> 然后再尝试一下

编译通过了，但是com.secretflow.spec.v1.ComponentDef这个包还是无法引用

**Comment by wenkesong-li** [comment]
是否正确按照上述步骤操作过~  
在项目根目录执行：mvn clean install -Dmaven.test.skip=true
正确按照步骤刷新过依赖 是可以的~

**Comment by tututt** [comment]
> mvn clean install -Dmaven.test.skip=true

可以了
