### ISSUE TITLE
secretpad 二分类逻辑回归预测结果是float

### ISSUE THREAD

**Issue by gxcuit** [secretflow/secretpad#50]
**Describe the bug**
我在使用逻辑回归或xgboost做训练时候，预测的pred 是float 而非是int， 有办法把predict 直接转换成0/1吗？

![image](https://github.com/secretflow/secretpad/assets/18736196/e1cbe659-e3a0-425b-a198-f09ecf4d2f26)
![image](https://github.com/secretflow/secretpad/assets/18736196/58bc91eb-3306-46ee-8f20-b56ff495cecc)

**Additional context**

**Comment by da-niao-dan** [comment]
你好，后面可以接一个case when 组件。自己设定一个threshold t， 小于t 为0，大于t为1。 case when 组件试用方法参考官网。

**Comment by gxcuit** [comment]
> 你好，后面可以接一个case when 组件。自己设定一个threshold t， 小于t 为0，大于t为1。 case when 组件试用方法参考官网。

  @da-niao-dan Hi,感谢您的回复。
我根据[文档](https://www.secretflow.org.cn/zh-CN/docs/secretpad/latest/pf7woou4dzgc90ol#i3Pp2)， “交叉决策”只能跟在求交之后吗？不能使用预测的输出，作为交叉决策的输入吗?  我的目的就是能够对预测进行0/1的转换

![image](https://github.com/secretflow/secretpad/assets/18736196/8053457a-b117-4dfd-acec-e083f73635d8)

**Comment by da-niao-dan** [comment]
你好，是的，目前交叉决策组件接受的类型必须是纵向表，但是预测输出的是单方表，不能直接接上。

但是前面所说的概念还是一样。

有以下几个选择
1. 如果希望测评，直接连二分类评估测评
2. 如果希望上生产，应该通过后续链路自行解决。（if else 逻辑）
3. 如果希望在secretpad上直接看到0和1的输出， 可以拿一个另一方的数据表，做一个求交再接一个交叉决策。

**Comment by gxcuit** [comment]
> 你好，是的，目前交叉决策组件接受的类型必须是纵向表，但是预测输出的是单方表，不能直接接上。
> 
> 但是前面所说的概念还是一样。
> 
> 有以下几个选择
> 
> 1. 如果希望测评，直接连二分类评估测评
> 2. 如果希望上生产，应该通过后续链路自行解决。（if else 逻辑）
> 3. 如果希望在secretpad上直接看到0和1的输出， 可以拿一个另一方的数据表，做一个求交再接一个交叉决策。

Thanks！ I will close this issue!!!
