### ISSUE TITLE
您好，请问pad组件能否构建横向联邦学习？

### ISSUE THREAD

**Issue by sion1989** [secretflow/secretpad#58]
目前pad组件的数据都需要求交后才能训练，如何假如要构建两方相同特征、不同ID的样本进行横向联邦学习，组件应该如何构建？

**Comment by Chrisdehe** [comment]
@sion1989 是的，请参考[平台组件说明](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/pf7woou4dzgc90ol#e4vcB)，汇总当前SecretPad平台组件，介绍说明每个组件的功能、组件连线、参数配置等

**Comment by sion1989** [comment]
close

**Comment by Chrisdehe** [comment]
@sion1989 hey，请问问题是否得到解决了？

**Comment by sion1989** [comment]
谢谢已了解目前组件的全部功能，确实不能构建横向联邦学习。
顺便提下[平台组件说明](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/pf7woou4dzgc90ol#e4vcB)中组件清单-》模型训练的几个模块输入输出桩描述和新版本的组件有点不一致，是否需要更新了？

**Comment by wenkesong-li** [comment]
目前pad中是不能构建横向联邦学习，secretflow是支持横向的，如果想要横向联邦学习可以自己进行二开。

感谢您的反馈，平台组件说明后续会进行相关更新~
