### ISSUE TITLE
secretpad本地使用mvn install出错

### ISSUE THREAD

**Issue by wangzeyu135798** [secretflow/secretpad#60]
![image](https://github.com/secretflow/secretpad/assets/39690172/76a6d352-0750-4bb9-8f42-f997c65ccb56)
![image](https://github.com/secretflow/secretpad/assets/39690172/6cfd18ea-5593-4a23-85c8-9bc53a4cd4e3)
![image](https://github.com/secretflow/secretpad/assets/39690172/679d7699-cbf4-44a8-a5e5-b7deba67832b)
在使用secretpad 0.6版本本地编译报错，请问该如何解决？

**Comment by Chrisdehe** [comment]
@wangzeyu135798 hey
看起来跟依赖有相关问题，请确认你的依赖版本是否对应[secretpad开发环境](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/mfbgum8vi3ngs4y9#hPJ96)

**Comment by wangzeyu135798** [comment]
![image](https://github.com/secretflow/secretpad/assets/39690172/9c1a75eb-9510-4745-9758-51cc0f761d9e)
![image](https://github.com/secretflow/secretpad/assets/39690172/f2312bbf-b674-455d-935d-4a7f3b126bd8)
我按照这个配置使用mvn clean install -Dmaven.test.skip=true 命令，版本配置和要求一样，但是还会出上面的错

**Comment by Chrisdehe** [comment]
@wangzeyu135798 请问是哪里出现的问题呢，是否得到解决？
