### ISSUE TITLE
secretpad本地调试 安装MVP闪退

### ISSUE THREAD

**Issue by wangzeyu135798** [secretflow/secretpad#62]
![image](https://github.com/secretflow/secretpad/assets/39690172/fc94264d-f5f5-4619-bf9f-839dcca79c91)
你好，我的后端版本如图所示。
tar -zxvf secretflow-allinone-package-latest.tar.gz
 cd secretflow-allinone-package-latest
 ./install
在install的时候，就会发生闪退，请问该如何解决？

**Comment by wenkesong-li** [comment]
你好  ~ 请参考安装指引 ./install 后面有相关参数需要传入~

https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/dbd670doqfio1puq
