### ISSUE TITLE
关于SecretPad的疑问

### ISSUE THREAD

**Issue by lijiaqi0121** [secretflow/secretpad#75]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
通过SecretPad All in One部署的平台，目前有以下几点疑问：
1、数据添加是只能上传csv文件吗，是否可以连接mysql数据库
2、训练好的模型发布之后，可以直接在平台上进行模型预测任务吗
3、模型发布时使用Http数据源，是只使用数据表的格式，还是每次预测时都会使用这个数据源
4、‘点击确定后，模型即可发布成功，可查看模型，并使用模型ID和endpoints构建特征服务API’，根据后面链接的文档地址https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.6.0b0/tutorial/run_sf_serving_with_api_cn，是具体在哪一步的时候使用模型ID和endpoints呢
```

**Comment by wenkesong-li** [comment]
1.数据源目前不支持mysql
2.现在不支持在平台上模型预测，只能在宿主机上和容器内进行黑屏使用
3. https://www.secretflow.org.cn/zh-CN/docs/serving/0.3.1b0/reference/spi
4.https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.6.0b0/tutorial/run_sf_serving_with_api_cn#id5

**Comment by lijiaqi0121** [comment]
好的，谢谢解答
