### ISSUE TITLE
模型数据源问题，是否支持oss云上资源供在线模型（http）和离线特征使用

### ISSUE THREAD

**Issue by john8628** [secretflow/secretpad#79]
### Issue Type

Running

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

linux centos

### All_in_one Version

v0.6

### Kuscia Version

kusia 0.7

### What happend and What you expected to happen.

```shell
背景：业务数据都在云上，是否支持在/离线模型调用
```

### Log output.

```shell
null
```

**Comment by pchyuan** [comment]
需要您对"在/离线模型调用"进一步的解释。
想确认下，您这边是通过云上的平台已经建模，希望对完成的模型，拿到其他地方使用？
还是说想了解：建模完成了，参与的多方（以两方为例），都自己拿着本地的模型就可以开展接下来的预算吗？

如果是后者，回答是纵向模型不可以。

**Comment by john8628** [comment]
> 需要您对"在/离线模型调用"进一步的解释。 想确认下，您这边是通过云上的平台已经建模，希望对完成的模型，拿到其他地方使用？ 还是说想了解：建模完成了，参与的多方（以两方为例），都自己拿着本地的模型就可以开展接下来的预算吗？
> 
> 如果是后者，回答是纵向模型不可以。

1:离线模型就是通过画布直接预测数据；但是数据源是在阿里云oss上；

2: 在线模型指的是通过pad将模型导出到本地，然后通过serving调用；但是部分数据源通过http方式获取；

**Comment by john8628** [comment]
> > > 需要您对"在/离线模型调用"进一步的解释。 想确认下，您这边是通过云上的平台已经建模，希望对完成的模型，拿到其他地方使用？ 还是说想了解：建模完成了，参与的多方（以两方为例），都自己拿着本地的模型就可以开展接下来的预算吗？
> > > 如果是后者，回答是纵向模型不可以。
> > 
> > 
> > 1:离线模型就是通过画布直接预测数据；但是数据源是在阿里云oss上；
> > 2: 在线模型指的是通过pad将模型导出到本地，然后通过serving调用；但是部分数据源通过http方式获取；
> 
> 1、预测之前一般有个建模的过程，oss数据源目前kuscia侧是支持的，但是还要看调用的算法组件本身是否支持。（即你用哪个算法？） 

1:想通过pad测，在管理数据源的地方添加oss数据，并在隐私求交用上

**Comment by zimu-yuxi** [comment]
> > 需要您对"在/离线模型调用"进一步的解释。 想确认下，您这边是通过云上的平台已经建模，希望对完成的模型，拿到其他地方使用？ 还是说想了解：建模完成了，参与的多方（以两方为例），都自己拿着本地的模型就可以开展接下来的预算吗？
> > 如果是后者，回答是纵向模型不可以。
> 
> 1:离线模型就是通过画布直接预测数据；但是数据源是在阿里云oss上；
> 
> 2: 在线模型指的是通过pad将模型导出到本地，然后通过serving调用；但是部分数据源通过http方式获取；

1.是否可以理解为在画布上使用相关算子做一个建模任务，但是想要使用oss数据源。如果是这样，目前pad页面没有添加oss数据源的口子。可以看下kuscia的[domaindatasource](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/reference/apis/domaindatasource_cn)的API，通过此API创建OSS数据源
2.在线预测服务目前我们是支持的，[在pad上训练好一个模型后发布](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.6.1b0/p2p_deploy/model_deployment)，可以[调用serving的A服务预测API](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.6.0b0/tutorial/run_sf_serving_with_api_cn#id5)做模型预测，但是暂时不支持OSS数据源的哈。目前pad数据管理的http数据源是指[特征数据源](https://www.secretflow.org.cn/zh-CN/docs/serving/0.3.1b0/topics/system/feature_service#feature-service)。
