### ISSUE TITLE
隐私求交时间过长

### ISSUE THREAD

**Issue by john8628** [secretflow/secretpad#85]
### Issue Type

Install/Deploy

### Have you searched for existing documents and issues?

Yes

### OS Platform and Distribution

centos

### All_in_one Version

latest

### Module type

secretpad

### Module version

1.5

### What happend and What you expected to happen.

```shell
隐私求交的过程，超过1个小时，数据量是140万行，数据A 23列，数据B 3列；机器配置8c16G；
```

### Log output.

```shell
正常logout
```

**Comment by zimu-yuxi** [comment]
可以提供下kuscia.log和stdout的日志吗，可以参考这个https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/deployment/logdescription

**Comment by john8628** [comment]
在kusia secreteflow的日志中，找到错误日志，应该是数据源的问题； 2024-06-12T17:18:44.677575872+08:00 stderr F    [Enforce fail at external/psi/psi/interface.cc:151] !check_csv_report.contains_duplicates. Input file /home/kuscia/var/storage/data/test0612_204725448.csv contains duplicates, please check duplicates at /tmp/42717568-2afa-42cd-90a4-d24be490ef30.psi_checked_duplicates

**Comment by john8628** [comment]
感谢支持
