### ISSUE TITLE
上传155M的文件，超时报错

### ISSUE THREAD

**Issue by john8628** [secretflow/secretpad#86]
### Issue Type

Others

### Have you searched for existing issues?

Yes

### Question Details

```shell
通过pad添加数据源报错，前端js超时告警
```

**Comment by wenkesong-li** [comment]
你好，可以提供下页面报错截图吗？

**Comment by john8628** [comment]
![img_v3_02bp_f9039e0a-949e-408f-b26c-69ccbac2fd0g](https://github.com/secretflow/secretpad/assets/8719716/a816c808-514c-430b-97b1-213a7b773715)

**Comment by john8628** [comment]
![img_v3_02bp_224413ea-4290-4882-a0ad-e3fd21fcbd6g](https://github.com/secretflow/secretpad/assets/8719716/c0814ab0-d7eb-4884-a11a-3982e4ad10c2)

**Comment by wenkesong-li** [comment]
你好，可以看下控制台是接口超时了还是前端报错了吗？

**Comment by john8628** [comment]
> 你好，可以看下控制台是接口超时了还是前端报错了吗？

pad里面没有任何的日志

**Comment by wenkesong-li** [comment]
你好，该问题已通过其他渠道反馈，由于我们这边没有复现到该问题，后续有新的进展将会给您反馈~

**Comment by zimu-yuxi** [comment]
经线下排查发现使用了nginx做了反向代理，nginx.conf文件上传大小配置没有指定，默认1M
解决方式：修改文件上传大小配置，client_max_body_size，发现用户server_name使用的是域名，让用户将本机hsots文件ip修改域名映射后解决

排查过程：和用户拉会投屏演示上传超时问题，50KB文件上传没有问题，10MB上传报错，并tail -f查看secretpad日志，发现上传报错时pad侧无日志输出，判断请求没有打到pad上，F12查看发现response是413 Request Entity Too Large，询问用户是否加了ngnix，用户查看后发现，由于端口冲突问题做了反向代理，因此判断ngnix配置存在问题，查看配置后，按照如上解决方式处理后解决
