### ISSUE TITLE
pad组件新增问题

### ISSUE THREAD

**Issue by oceanqdu** [secretflow/secretpad#88]
场景：在secretflow中自定义了一个无输入的组件想在secretpad中进行使用，在secretflow中使用pytest测试均通过 ，在集成到secretpad中心化部署时使用时出现如下问题：
![image](https://github.com/secretflow/secretpad/assets/49178688/462a55bc-59db-4248-a488-6322838a6948)
怎么在secretpad中指定组件的initor？
组件类似于样本表组件，是一个无输入的组件

**Comment by wenkesong-li** [comment]
你好，请问一下 无输入的组件 是没有输入桩  还是 没有配置项？

如果是没有输入桩的话，pad 现在还不支持，如果是没有配置项的话 是可以正常跑的

**Comment by oceanqdu** [comment]
@wenkesong-li 是没有输入桩，但是有配置项的，输入桩的目的是为了标识initor的吗？是否可以通过配置项来配置initor

**Comment by oceanqdu** [comment]
![image](https://github.com/secretflow/secretpad/assets/49178688/de0dbd97-d475-4925-9de2-d8ce52ae857d)

执行psi组件的时候出现以上问题，secretflow中镜像中psi的版本已经为0.05，如何修改pad中的组件版本？

**Comment by Chrisdehe** [comment]
已解决，问题原因是已有的训练流中psi版本为0.0.4 ，更新镜像以后psi版本为0.0.5 ，更新后运行了0.0.4版本的训练流导致任务失败。
