### ISSUE TITLE
关于MVP部署包的WOE分箱问题

### ISSUE THREAD

**Issue by mtl802** [secretflow/secretpad#9]
我是使用的是0.2版本，数据都是测试数据集。使用的也是“金融风控模板”
配置应该也没什么问题，但是一运行到WOE分箱后就出错，报错如下：
![image](https://github.com/secretflow/secretpad/assets/20579710/0a5e84fd-9ebf-44a9-ab96-44d5c0315d4b)

**Comment by UniqueMarvin** [comment]
你好，这个报错的可能原因是 你在数据授权时 alice方也选择了label，使用自带的实验数据时 alice 侧不需要选择 label列，只有bob侧的bob.csv 的y列是label列
<img width="1351" alt="image" src="https://github.com/secretflow/secretpad/assets/22186553/df9b64c9-aeac-40e2-af90-0ed3c0850c00">
<img width="1602" alt="image" src="https://github.com/secretflow/secretpad/assets/22186553/58475926-59d4-4508-a010-b4a58e83a57e">
<img width="832" alt="image" src="https://github.com/secretflow/secretpad/assets/22186553/42b2b259-b2f3-4983-a659-17f962ff979d">

**Comment by mtl802** [comment]
> 你好，这个报错的可能原因是 你在数据授权时 alice方也选择了label，使用自带的实验数据时 alice 侧不需要选择 label列，只有bob侧的bob.csv 的y列是label列 <img alt="image" width="1351" src="https://user-images.githubusercontent.com/22186553/270211580-df9b64c9-aeac-40e2-af90-0ed3c0850c00.png"> <img alt="image" width="1602" src="https://user-images.githubusercontent.com/22186553/270211728-58475926-59d4-4508-a010-b4a58e83a57e.png"> <img alt="image" width="832" src="https://user-images.githubusercontent.com/22186553/270213151-42b2b259-b2f3-4983-a659-17f962ff979d.png">

问题已排查，感谢
